### ISSUE TITLE
从v2ex上的讨论沉浸式翻译没开源的评论区来的

### ISSUE THREAD

**Issue by yhx0022** [fishjar/kiss-translator#1]
希望开发者有余力的话，除了浏览器扩展，也随便做个翻译的油猴脚本。

**Comment by Tohrusky** [comment]
字词作者

**Comment by oeieo** [comment]
加油，等着呢

**Comment by fishjar** [comment]
看了油猴的文档，感觉不是简单的迁移，之前没考虑过这个需求，需要调整的地方很多。
不过还是会尝试下的，看看如何尽量复用代码的情况下做一个能用的版本。

**Comment by leic4u** [comment]
作者加油，已经 Star 支持。期待早日上架 Chrome / Egde / Firefox 的扩展商店。上架那天，我在 V 站给项目开贴作推广。

PS：如果你也要转闭源的时候，记得在项目 readme 里提醒一下大家 [狗头]

**Comment by fishjar** [comment]
从 `v1.3.1` 开始支持油猴脚本，目前 `Chrome` + `Tampermonkey` 测试通过，其他场景期待大家测试
