### ISSUE TITLE
deepl api无法使用

### ISSUE THREAD

**Issue by cangkuai** [fishjar/kiss-translator#101]
目前chrome 123版本里面使用deepl会导致因为跨域导致请求失败
![QQ截图20240329114344](https://github.com/fishjar/kiss-translator/assets/33569578/a7868085-be5c-4d9a-90ec-d0581f112ff1)

**Comment by fishjar** [comment]
这个很奇怪，按理`background.js`中的请求不会有跨域问题。而且我这里没有遇到这个情况，你能否再试试。

**Comment by cangkuai** [comment]
是不是你chrome版本太低的原因，我目前windows和linux都能稳定复现

**Comment by fishjar** [comment]
到接口设置那里，点`点击测试`，也出现吗？

**Comment by cangkuai** [comment]
会出现

**Comment by cangkuai** [comment]
chrome版本为
版本 123.0.6312.86（正式版本） （64 位）

**Comment by fishjar** [comment]
我升级到和你一样的版本，没有出现跨域错误，只是我没有key，接口正常返回403。

你是否自己编译的，修改过配置文件？

**Comment by cangkuai** [comment]
过于逆天，我删了从新装一遍就没问题了

**Comment by cangkuai** [comment]
找到问题了，如果可读性设置为当您点击此拓展程序时的话就会出现，如果设置为在所有网站上就没问题了

**Comment by fishjar** [comment]
> ```
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://xxx. (Reason: CORS preflight response did not succeed). Status code: 404.
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://xxx. (Reason: CORS request did not succeed). Status code: (null).
> ```
> 
> Firefox 油猴脚本 存在跨域问题，无法使用deeplx

自行下载脚本：https://greasyfork.org/zh-CN/scripts/472840-kiss-translator/code

然后将域名添加进去：
![Screenshot from 2024-05-20 21-13-17](https://github.com/fishjar/kiss-translator/assets/1157624/16e8aa9f-8688-452e-a6b4-3a95df63990c)

**Comment by fishjar** [comment]
> @fishjar 换成扩展版后OK了，但是有几个问题
> 
> 1. 自动判断会通过百度来实现，这个会有隐私和安全问题

对，目前远程语言识别用的是百度的接口，后面可以考虑多接入几个，供用户选择。

> 2. 现在的自动判断是这样的 `{"text":"test","target_lang":"ZH","source_lang":""}`，但是 `source_lang` 需要传递 `auto`，似乎在设置中无法实现

在规则设置中，“原文语言”选择`auto-detect`。

> 3. 似乎划词翻译无论如何都会调用百度翻译，没有地方关闭吗？

暂时无法关闭。
划词翻译如果选中的是单词，会调用百度的词典接口。
另外，不管是单词还是句子，都会调用百度的一个关联词接口，展示更多信息。

如果有隐私担忧，如前所述，后续可以给多几个其他接口选择，或关闭选项的选择。

**Comment by fishjar** [comment]
> > 在规则设置中，“原文语言”选择`auto-detect`。
> 
> 选择`auto-detect`传递的就是空白 `source_lang: ""`

部分翻译服务不需要`auto`，所以会转换成空字符串。
不过这里可能有个bug，发现`DeepLX`和`DeepLFree`的处理不一致。

![Screenshot from 2024-05-21 10-36-02](https://github.com/fishjar/kiss-translator/assets/1157624/e1263589-b8d0-495e-bc92-7a4ef484d680)

**Comment by fishjar** [comment]
我不确定你的deeplx接口是否一定要设定为`auto`，还是说空字符串也可以工作，能否确认一下。

**Comment by fishjar** [comment]
> > 我不确定你的deeplx接口是否一定要设定为`auto`，还是说空字符串也可以工作，能否确认一下。
> 
> 必须要`auto`，不能是空
> 
> ```
> {
>     "text": "text to be translated",
>     "source_lang": "auto",
>     "target_lang": "ZH"
> }
> ```

有点奇怪，我之前测试过本地跑的deeplx，貌似不需要`auto`。
那你暂时用自定义接口设置吧，要下个版本再更新为`auto`。
不过自定义接口不能配置多URL轮寻，

**Comment by fishjar** [comment]
> > 有点奇怪，我之前测试过本地跑的deeplx，貌似不需要`auto`。
> 
> 因为这个是deeplx在画蛇添足，deepl本身是要求auto的，这种东西一定要按照deepl的标准来
> 
> https://github.com/OwO-Network/DeepLX/blob/main/translate.go#L89

实际官方文档也没有明确说是`auto`，只是说可以省略，如果按照省略的意思，空字符串反而更合理：
https://developers.deepl.com/docs/api-reference/translate

![Screenshot from 2024-05-21 11-06-24](https://github.com/fishjar/kiss-translator/assets/1157624/e4b91f35-0bac-4ddb-8928-3969f0620046)

**Comment by fishjar** [comment]
明白，下个版本deeplx改为`auto`。

**Comment by fishjar** [comment]
> > 明白，下个版本deeplx改为`auto`。
> 
> 可以先更新一个修复版吗，现在每个网页都要手动在设置里指定语言才能翻译，重复次数多了有点折磨

可以通过自定义接口应急：

request hook

```js
(text, from, to, url, key) => [
  url,
  {
    headers: {
      "Content-type": "application/json",
    },
    method: "POST",
    body: JSON.stringify({
      text,
      target_lang: "ZH",
      source_lang: "auto",
    }),
  },
]
```

response hook

```js
(res, text, from, to) => [res.data, "ZH" === res.source_lang]
```
