### ISSUE TITLE
希望增加个点击翻译弹窗外空白处，自动关闭弹窗的功能

### ISSUE THREAD

**Issue by EsuRt** [fishjar/kiss-translator#105]
目前只能点击翻译弹窗的关闭按钮，才能关闭弹窗，划词翻译使用频繁的情况下，比较麻烦，希望能增加个在空白处点击，自动关闭弹窗的功能。

**Comment by fishjar** [comment]
> 目前只能点击翻译弹窗的关闭按钮，才能关闭弹窗，划词翻译使用频繁的情况下，比较麻烦，希望能增加个在空白处点击，自动关闭弹窗的功能。

我一般习惯缩放到合适大小后拖到网页的旁边，不会遮挡正文，也就不需要关闭了。
不过你这个需求我也考虑下。

**Comment by fishjar** [comment]
下个版本将增加一个可选设置，点击外部关闭弹窗。

**Comment by EsuRt** [comment]
多谢，新版本用起来很棒，不知能否再增加个移动到划词翻译图标自动翻译的功能？

**Comment by fishjar** [comment]
应该没问题，可以增加一个选项，是点击翻译还是移上去就翻译。

**Comment by EsuRt** [comment]
问题完美解决，多谢大佬。
