### ISSUE TITLE
默认规则是默认开启的，能改成 * 跟随用户设置么？

### ISSUE THREAD

**Issue by everyx** [fishjar/kiss-translator#11]
我想只在我开启（Alt+Q）的时候再开启，其他时候关闭，能否增加一个选项覆盖默认规则的「开启设置」？

**Comment by fishjar** [comment]
大概明白你的意思，我考虑下看看怎么改比较好。

**Comment by BIMiracle** [comment]
+1 需要默认不开启，Alt+Q才翻译当前页面，因为大部分网站都不需要翻译

**Comment by benzBrake** [comment]
+1 ，比如 Github，平常是不需要翻译的，只有看文档的时候才需要翻译

**Comment by fishjar** [comment]
[v1.6.1](https://github.com/fishjar/kiss-translator/releases/tag/v1.6.1) 已经支持覆写订阅规则了，可以将`开启翻译`关闭。

**Comment by everyx** [comment]
@fishjar 👍，请问一般多长时间会更新到 Firefox 附加组件呢？

**Comment by fishjar** [comment]
> @fishjar 👍，请问一般多长时间会更新到 Firefox 附加组件呢？

这个时间没法确定，我不是每个版本都会提交到各个插件市场，而且各个市场的审核时间也很不一致。

下一个递交到插件市场的版本预计是 v1.6.2 或 v1.6.3

**Comment by benzBrake** [comment]
> > @fishjar 👍，请问一般多长时间会更新到 Firefox 附加组件呢？
> 
> 这个时间没法确定，我不是每个版本都会提交到各个插件市场，而且各个市场的审核时间也很不一致。
> 
> 下一个递交到插件市场的版本预计是 v1.6.2 或 v1.6.3

能不能打包成未签名的xpi，Firefox可以破解签名限制，这样就不用等审核了

**Comment by fishjar** [comment]
发现 Firefox 的审核是秒过啊，刚上传，已经是最新版了： https://addons.mozilla.org/zh-CN/firefox/addon/kiss-translator/

**Comment by fishjar** [comment]
Chrome 也很快了，不到半小时通过审核： https://chrome.google.com/webstore/detail/kiss-translator/bdiifdefkgmcblbcghdlonllpjhhjgof?hl=zh-CN
