### ISSUE TITLE
无法翻译shadow DOM节点

### ISSUE THREAD

**Issue by cokefis** [fishjar/kiss-translator#113]
例如下面网址:
[Tsunami alert after a volcano in Indonesia has several big eruptions and thousands are told to leave](https://www.msn.com/en-us/weather/topstories/tsunami-alert-after-a-volcano-in-indonesia-has-several-big-eruptions-and-thousands-are-told-to-leave/ar-BB1lNX7Y)

**Comment by fishjar** [comment]
试试这个选择器：

```css
*  >>> :is(li, p, h1, h2, h3, h4, h5, h6, dd, blockquote, .card-title)
* ```

**Comment by fishjar** [comment]
或者这个：

```css
views-header-wc,cp-article,desktop-feed-views >>> :is(li, p, h1, h2, h3, h4, h5, h6, dd, blockquote, .card-title)
```

**Comment by rxliuli** [comment]
@fishjar  也许使用 query-selector-shadow-dom 之类的查询工具自动穿透所有 shadow dom？现在对于多层的 shadow dom 编写规则很痛苦，例如 reddit，到处都是 shadow dom
