### ISSUE TITLE
某些页面翻译内容滚动时会消失，停止滚动会再出现

### ISSUE THREAD

**Issue by everyx** [fishjar/kiss-translator#12]
例如：https://m3.material.io/components/all-buttons

规则：`mio-carbon-component>>>li,p,th,td,h1,h2,h3`

[录屏 2023-08-30 10-39-07.webm](https://github.com/fishjar/kiss-translator/assets/1665522/55f3d779-5a90-4dd3-9265-9a58499b62e3)

**Comment by fishjar** [comment]
我看了下好像是页面本身的问题，滚动的时候，部分页面元素会重新渲染，所以会重新翻译。

**Comment by everyx** [comment]
看起来是的，这个网站有些页面正常，有些就会重新渲染
