### ISSUE TITLE
在YouTube直播信息栏中无法呼出翻译按钮

### ISSUE THREAD

**Issue by swttkonjjj** [fishjar/kiss-translator#121]
![image](https://github.com/fishjar/kiss-translator/assets/66727004/0a3a2bf7-9eca-49e8-830b-29f9b9ff74fd)
在直播中划词翻译和全文翻译都无法唤出

**Comment by fishjar** [comment]
这个是选择器问题，同步下一下订阅规则即可。

**Comment by swttkonjjj** [comment]
![image](https://github.com/fishjar/kiss-translator/assets/66727004/d8c0ab16-e569-401c-87a3-31632f159477)
👍
