### ISSUE TITLE
"展開/隱藏"的內文，無法全面翻譯

### ISSUE THREAD

**Issue by leadra** [fishjar/kiss-translator#124]
![image](https://github.com/fishjar/kiss-translator/assets/67009996/5e9a89aa-53d5-444b-a3a3-d67aee69e8df)
https://greasyfork.org/zh-TW/scripts/478248-twitter%E3%82%92%E5%B0%91%E3%81%97%E4%BE%BF%E5%88%A9%E3%81%AB
在腳本頁面，有部分日文沒翻譯，似乎跟"展開/隱藏"有關係

**Comment by fishjar** [comment]
这种网页结构非常杂乱，规则设置仅供参考：
![Screenshot from 2024-05-18 22-53-04](https://github.com/fishjar/kiss-translator/assets/1157624/ed4b56b4-07b4-4442-afa8-bf362288fa64)

效果：
![Screenshot from 2024-05-18 22-54-47](https://github.com/fishjar/kiss-translator/assets/1157624/59411a4c-32f6-4d89-aae8-5431e837eae3)

**Comment by leadra** [comment]
感謝教學~!
他的html代碼太多吧~
的確可以全部翻譯了
不過要自動翻譯有打開，如果預設關閉，載入後才用快速鍵翻譯，就一樣會缺
但這樣也夠了，感謝~^^
![image](https://github.com/fishjar/kiss-translator/assets/67009996/c8e629aa-fb12-4eeb-a894-2f71fdb91d3c)

更正，手動翻譯的話，第一次會缺，再關閉後打開第二次就可以完整翻譯了~^^

**Comment by leadra** [comment]
![image](https://github.com/fishjar/kiss-translator/assets/67009996/5151f330-1a9c-45e4-8e9f-f60e35ae4a5e)
不好意思，沒找到相關教學
想請教能否排除關鍵字，YT的表情符號，會重複一次+代碼都翻譯出來

**Comment by fishjar** [comment]
> ![image](https://private-user-images.githubusercontent.com/67009996/332424690-d1dfb7f8-0d94-40ed-b6f7-cf12528d0f75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyOTU1NjQsIm5iZiI6MTcxNjI5NTI2NCwicGF0aCI6Ii82NzAwOTk5Ni8zMzI0MjQ2OTAtZDFkZmI3ZjgtMGQ5NC00MGVkLWI2ZjctY2YxMjUyOGQwZjc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDEyNDEwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzYzljMjczOTBmODc2OTE0NzYyNWU2ZjZkMGRhNWViNGQ2MGU3NzNjZDQxN2NmNDkzMzVkZmY4ZGQyNWVjYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u4LzOuzz50z64SBsJ2JhOaC-u0s_1Thk2Yeqym1PgCs) 不好意思，沒找到相關教學 想請教能否排除關鍵字，YT的表情符號，會重複一次+代碼都翻譯出來

这是YT的直播讨论？能否发个链接

**Comment by fishjar** [comment]
我打开没发现你说的问题

![Screenshot from 2024-05-21 23-20-59](https://github.com/fishjar/kiss-translator/assets/1157624/f077dcb1-dece-48b3-ac06-5585139b4953)

**Comment by leadra** [comment]
![image](https://github.com/fishjar/kiss-translator/assets/67009996/c094232b-1e6a-41ee-a26f-0ccd0788c13f)
剛發覺，滑鼠移入符號cover才翻譯，以為是別的功能，後來把劃詞、輸入框翻譯關閉，也仍然一樣翻譯
![image](https://github.com/fishjar/kiss-translator/assets/67009996/c71cb666-f6f3-4929-b0ae-15c80e95a432)

**Comment by leadra** [comment]
![image](https://github.com/fishjar/kiss-translator/assets/67009996/3b4d179d-2a5d-4ec6-8917-180e11b08506)
會不會是因為，移入YT會有表情的代碼提示，所以導致翻譯

**Comment by fishjar** [comment]
找到原因了，是鼠标移上去会添加一个元素。稍后同步下订阅规则即可

**Comment by leadra** [comment]
感謝，成功了~

**Comment by leadra** [comment]
https://shinengumi.booth.pm/items/5769881
不好意思又麻煩作者
中間的內容無法翻譯
順帶問要怎麼自己找出對應元素呢，是否類似這個
![image](https://github.com/fishjar/kiss-translator/assets/67009996/883d746c-e940-4524-a930-267c4976ca65)

![image](https://github.com/fishjar/kiss-translator/assets/67009996/1e0e7119-5888-4f2e-bea6-6ead7f1bcd00)

**Comment by leadra** [comment]
非常感謝，原來還有修復要增加

**Comment by fishjar** [comment]
保留元素选择器不是这样用的，这个主要作用保留行内元素用的。

不想翻译标题，去掉选择器的`h1`即可

**Comment by leadra** [comment]
感謝~去除這些後，就不會翻譯標題了
h1>.ytd-watch-metadata, #video-title, #title,

另外，由於安裝了腳本[Tabview Youtube](https://greasyfork.org/zh-TW/scripts/428651-tabview-youtube)
將description表單化，所以不會翻譯了，只是選擇的元素加了都無效
description,content,right-tabs,tab-content-cld
![image](https://github.com/fishjar/kiss-translator/assets/67009996/15771ad5-5a77-49ea-bfa0-9e0e774e1a6d)

不過原本的翻譯情況，是在所有內容的最下方才翻譯
目前我都是用CENT (CHROME內建的GOOGLE翻譯)看
![image](https://github.com/fishjar/kiss-translator/assets/67009996/2cf34e54-204a-4f83-b90a-2f260dfd6344)

**Comment by leadra** [comment]
另外發現社群的貼文無法翻譯
https://www.youtube.com/@HoshimachiSuisei/community
![image](https://github.com/fishjar/kiss-translator/assets/67009996/b725bb1b-3f1d-4685-84a6-f81e23ffe807)

大概會員貼文是一樣的元素，到時候測試
![image](https://github.com/fishjar/kiss-translator/assets/67009996/ce84e3ec-12e9-49ac-8116-3e72d5677478)

**Comment by fishjar** [comment]
> 另外發現社群的貼文無法翻譯 https://www.youtube.com/@HoshimachiSuisei/community ![image](https://private-user-images.githubusercontent.com/67009996/333760660-b725bb1b-3f1d-4685-84a6-f81e23ffe807.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MjYyMjAsIm5iZiI6MTcxNjcyNTkyMCwicGF0aCI6Ii82NzAwOTk5Ni8zMzM3NjA2NjAtYjcyNWJiMWItM2YxZC00Njg1LTg0YTYtZjgxZTIzZmZlODA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDEyMTg0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyZDU0ZjNjYTc3YjExZDE4MTc5NGJiODI4MTAwNWY3MDhkMjVkMDFjYTBlOWIzYTJhMjNjZTI1NWZhY2YxZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AWAGecyv_LUZnndEF-6e1KyriuITep5ObNoOI2dJWU0)
> 
> 大概會員貼文是一樣的元素，到時候測試 ![image](https://private-user-images.githubusercontent.com/67009996/333760785-ce84e3ec-12e9-49ac-8116-3e72d5677478.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MjYyMjAsIm5iZiI6MTcxNjcyNTkyMCwicGF0aCI6Ii82NzAwOTk5Ni8zMzM3NjA3ODUtY2U4NGUzZWMtMTJlOS00OWFjLTgxMTYtM2U3MmQ1Njc3NDc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDEyMTg0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2YTM0M2Q2Mjc3MDI4ZDI0YmQwNDBkMTgxYjI4Zjc3MzQzZjYxN2UxMzdjMjZlMzNlODI5ODY1ZDlmZmIxM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xA2t6MIrLpLtn6ov6e8LBHzjHw1tovuz5mfuGr8DcMo)



选择器那里，添加一条 `, .ytd-backstage-post-renderer`

**Comment by fishjar** [comment]
youtube的页面结构也是挺杂乱的，有些细节的地方，建议用划词翻译

**Comment by leadra** [comment]
感謝，社群成功翻譯了，雖然頭像分裂了ww
反正不影響閱讀
![image](https://github.com/fishjar/kiss-translator/assets/67009996/fa4575f7-7700-4452-9b0b-4c57d60d2904)

的確，有些小地方用划词翻译就好了
YT亂七八糟~~

辛苦了

**Comment by leadra** [comment]
請教關於無法斷行
討論的內文增加了.user-content，可以翻譯了，但是會所有內容塞一起，修復函數之前有設"br"。
PS.如果太複雜就略過，就靠網頁或划词翻譯
https://greasyfork.org/zh-TW/scripts/428651-tabview-youtube/discussions/241157
![image](https://github.com/fishjar/kiss-translator/assets/67009996/2dd9204c-feeb-4f8a-9134-c4f7db978a24)

**Comment by fishjar** [comment]
> 請教關於無法斷行 討論的內文增加了.user-content，可以翻譯了，但是會所有內容塞一起，修復函數之前有設"br"。 PS.如果太複雜就略過，就靠網頁或划词翻譯 https://greasyfork.org/zh-TW/scripts/428651-tabview-youtube/discussions/241157 ![image](https://private-user-images.githubusercontent.com/67009996/333926518-2dd9204c-feeb-4f8a-9134-c4f7db978a24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3ODE3ODIsIm5iZiI6MTcxNjc4MTQ4MiwicGF0aCI6Ii82NzAwOTk5Ni8zMzM5MjY1MTgtMmRkOTIwNGMtZmVlYi00ZjhhLTkxMzQtYzRmN2RiOTc4YTI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDAzNDQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3NGRhMDgzZTFlMmE0NDZhYTQ0ZjNhODMzNGUwYTk3MDUzZGUxY2UyYjU2N2MzYmIyODEwMDc3NDc0NGRlYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VULBXqPKKuKe-hcH275ADUw0Ttd_RFSEYymfRXmGs7s)

选择器用 `h2, .script-link, .script-description, :is(li, p, h1, h2, h3, h4, h5, h6, dd, blockquote, .kiss-p)` 试试

greasyfork.org的页面也是挺乱的，很难完美

**Comment by leadra** [comment]
喔喔，原來是把這個刪去就好#additional-info 
的確，大部分，純文字的可以正常翻譯，但有插入圖片[img src]，就會擠一團，或是略過沒翻。
辛苦了，我用其他補完吧
![image](https://github.com/fishjar/kiss-translator/assets/67009996/4f6854ad-da5b-4c79-9754-ff0ae5982b7e)
![image](https://github.com/fishjar/kiss-translator/assets/67009996/b13d1798-505c-4ae4-8a1a-b1accc2481f0)

**Comment by leadra** [comment]
補充說明:
大概是內容有{}還是//  導致翻譯不能斷行
https://greasyfork.org/zh-TW/scripts/27308-youtube-html5-auto-loop
![image](https://github.com/fishjar/kiss-translator/assets/67009996/931a1d79-de5e-48e1-bf2f-5f395972c734)

**Comment by fishjar** [comment]
1、翻译不能断行的原因是页面的代码使用了<br> 来换行，而不是使用常规的<p>。
2、本插件可以通过网页修复解决这个问题，比如下面的例子，可以增加一个`br`网页修复函数，选择器写`#additional-info>p`即可。
3、但是该网站的`additional-info`部分其实是用户编辑的，这样几乎每个页面都要写一套适配规则，很不划算。
4、类似的还有论坛也是，内容由用户通过富文本编辑器自由编辑，结构都很乱，不要抱着完美翻译的期望。

![Screenshot from 2024-05-29 08-26-32](https://github.com/fishjar/kiss-translator/assets/1157624/908d5160-2521-4cd8-930e-ff1415d3cf03)

**Comment by leadra** [comment]
了解，感謝~
其實純文字能翻譯就夠了，那些圖片cod複雜交錯的細節，就划词翻譯補充就好了
真是辛苦了，有這個簡約翻譯真的讚

**Comment by leadra** [comment]
請問fanbox的內文也能支援翻譯嗎?
是公開的貼文
https://hozonsui.fanbox.cc/posts/8043419?utm_campaign=post_page
![image](https://github.com/fishjar/kiss-translator/assets/67009996/a342351d-33bc-43ac-bca2-583318dbc22e)

**Comment by fishjar** [comment]
试试 
···css
h1, [data-text="true"]
···

**Comment by leadra** [comment]
成功了感謝~
![image](https://github.com/fishjar/kiss-translator/assets/67009996/66f7138c-71ee-4046-a487-68f9b7916467)
