### ISSUE TITLE
chrome浏览器下载时出错：Image decode failed

### ISSUE THREAD

**Issue by xiao-xiaozi** [fishjar/kiss-translator#129]
![image](https://github.com/fishjar/kiss-translator/assets/50149380/e4618e8e-ad77-4fc7-b7ae-66037c05dcab)

chrome版本号： 124.0.6367.208

**Comment by fishjar** [comment]
没遇到过这个问题，多尝试下看看

**Comment by xiao-xiaozi** [comment]
真是神奇、昨天试了好几次都不行。今天重试下，一次就成功了。
