### ISSUE TITLE
一点优化小意见

### ISSUE THREAD

**Issue by xiaoguyu** [fishjar/kiss-translator#13]
插件很好用，非常感谢作者。以下一些优化意见，也是个人非常希望添加的功能。
1. 允许用户选择是否开启翻译
    现在是默认开启，刷新一次页面就需要手动关一次
2. 增加开关快捷键

我的使用场景是默认关（一些简单和经常浏览的英文网站不需要开翻译），有需要再手动开

**Comment by fishjar** [comment]
1、你的需求应该和 https://github.com/fishjar/kiss-translator/issues/11 的差不多
2、浏览器插件是支持快捷键的`Alt+Q`

**Comment by xiaoguyu** [comment]
好的，感谢您的解答
