### ISSUE TITLE
有关于如何进行规则配置的文档吗？

### ISSUE THREAD

**Issue by bigshans** [fishjar/kiss-translator#136]
在给 MDN 配置翻译，因为一些内容在默认规则下没有翻译。

https://developer.mozilla.org/en-US/docs/Web/API/Attribution_Reporting_API

配置半天没有太明白规则是怎么回事，特别是列表那里。这个网页有列表篏列表的结构，结果第一层列表没有翻译，第二层翻译了。我配置让它仅对列表生效而不管每一项，结果第一层翻译了，但第二层没有翻译好。

**Comment by fishjar** [comment]
添加一个br修复函数，网页修复选择器填：
```css
ol>li
```

**Comment by bigshans** [comment]
> 添加一个br修复函数，网页修复选择器填：
> 
> ```css
> #content li:has(li)
> ```
> 
> ![Screenshot from 2024-06-06 08-42-19](https://private-user-images.githubusercontent.com/1157624/336930084-0498d381-f9d3-4082-be12-8188cb45e84e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NDI3MzAsIm5iZiI6MTcxNzY0MjQzMCwicGF0aCI6Ii8xMTU3NjI0LzMzNjkzMDA4NC0wNDk4ZDM4MS1mOWQzLTQwODItYmUxMi04MTg4Y2I0NWU4NGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDZUMDI1MzUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTdlY2MzZDU1YmQ3YjcxYWY4ZmVjYmQwMmMwMzM1NDc2N2EzMWI2YWFhOTg1NDI2NzYyMzgyZDU5ZTllY2UzZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.yKptddr-5ge_C0Ob-U9Xxo4_Xcu4JGjpqXRqPROSj_I)

感谢！配置出来了。
