### ISSUE TITLE
为什么这个插件总是自动翻译我的网站啊？

### ISSUE THREAD

**Issue by lovetingyuan** [fishjar/kiss-translator#139]
我不想让它自动翻译，我想关闭所有的自动翻译，请问我应该怎么配置？我实在找不到配置的开关

**Comment by lovetingyuan** [comment]
并且我不想让这个悬浮小球出现，请问怎么关闭（疑问：这种有点侵入性的功能点应该默认关闭比较好吧？）

**Comment by fishjar** [comment]
> 我不想让它自动翻译，我想关闭所有的自动翻译，请问我应该怎么配置？我实在找不到配置的开关

参考这里：https://github.com/fishjar/kiss-translator/issues/127#issuecomment-2122547749

**Comment by fishjar** [comment]
> 并且我不想让这个悬浮小球出现，请问怎么关闭（疑问：这种有点侵入性的功能点应该默认关闭比较好吧？）

基本设置那里，选择隐藏悬浮按钮
