### ISSUE TITLE
Firefox Android 中设置页面（网页）显示异常

### ISSUE THREAD

**Issue by HashLiver** [fishjar/kiss-translator#14]
![IMG_20230830_191209](https://github.com/fishjar/kiss-translator/assets/42889797/ce4e9d66-4647-46c6-accf-a42a0e4cba37)

如图所示，网页`https://fishjar.github.io/kiss-translator/options.html`显示异常，无法进行设置。

**Comment by fishjar** [comment]
昨天我也发现了，可能要等等，v1.6版才会解决。

**Comment by HashLiver** [comment]
我觉得还是把设置项全部移到本地比较好。
很多浏览器扩展，像是著名的去广告扩展uBlock Origin虽然有全屏的设置界面，但都是本地页面（比如以uBlock Origin为例，在Firefox上的设置页面是`moz-extension://********/dashboard.html#settings.html`），而那什么「沉浸式翻译」选择把设置放在网页上就是纯粹是为了能开会员收米。

**Comment by fishjar** [comment]
1、花力气把设置页面分离出来主要是为了减小脚本体积。你说的担心页面挂掉的情况我也考虑过，所以多部署了一份，都是大公司的免费服务，两个同时挂掉的可能性比较小吧

- github pages: https://fishjar.github.io/kiss-translator/options.html
- cloudflare pages: https://kiss-translator.rayjar.com/options

2、firefox上的这个问题不是网页访问异常，而是浏览器差异造成的bug
