### ISSUE TITLE
Bloomberg的标题翻译不了

### ISSUE THREAD

**Issue by toyo2333** [fishjar/kiss-translator#144]
https://www.bloomberg.com/opinion/articles/2024-06-15/hong-kong-and-singapore-are-incomparable-financial-centers

鼠标悬停翻译

标题：Hong Kong and Singapore Are Not the Same
出现... 之后，就消失了。

但是下面的：They sit in very different corners of the financial system. The rise of one doesn’t spell the demise of the other. 
这一行就可以翻译并显示。

**Comment by fishjar** [comment]
再试试，没发现你说的情况。
