### ISSUE TITLE
Doesn't work on FireFox with Violentmonkey

### ISSUE THREAD

**Issue by fuzy112** [fishjar/kiss-translator#15]
<details><summary>Details</summary>
<p>

[load injectRules] ReferenceError: caches is not defined
    _callee5$ moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:19725
    tryCatch moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17145
    makeInvokeMethod moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17233
    defineIteratorMethods moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17174
    asyncGeneratorStep moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17407
    _next moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17426
    promise callback*asyncGeneratorStep moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17416
    _next moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17426
    asyncToGenerator_asyncToGenerator moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17431
    asyncToGenerator_asyncToGenerator moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17423
    fetchData moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:19725
    _callee6$ moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:19730
    tryCatch moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17145
    makeInvokeMethod moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17233
    defineIteratorMethods moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17174
    asyncGeneratorStep moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17407
    _next moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17426
    asyncToGenerator_asyncToGenerator moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17431
    asyncToGenerator_asyncToGenerator moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17423
    fetchPolyfill moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:19730
    _callee$ moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:19744
    tryCatch moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17145
    makeInvokeMethod moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17233
    defineIteratorMethods moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17174
    asyncGeneratorStep moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17407
    _next moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17426
    asyncToGenerator_asyncToGenerator moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17431
    asyncToGenerator_asyncToGenerator moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17423
    fetch moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:19744
    _callee5$ moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:19748
    tryCatch moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17145
    makeInvokeMethod moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17233
    defineIteratorMethods moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17174
    asyncGeneratorStep moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17407
    _next moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17426
    asyncToGenerator_asyncToGenerator moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17431
    asyncToGenerator_asyncToGenerator moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17423
    syncSubRules moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:19748
    _callee8$ moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:19761
    tryCatch moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17145
    makeInvokeMethod moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17233
    defineIteratorMethods moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17174
    asyncGeneratorStep moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17407
    _next moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17426
    promise callback*asyncGeneratorStep moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17416
    _next moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17426
    asyncToGenerator_asyncToGenerator moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17431
    asyncToGenerator_asyncToGenerator moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17423
    loadSubRules moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:19761
    _callee5$ moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:19780
    tryCatch moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17145
    makeInvokeMethod moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17233
    defineIteratorMethods moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17174
    asyncGeneratorStep moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17407
    _next moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17426
    asyncToGenerator_asyncToGenerator moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17431
    asyncToGenerator_asyncToGenerator moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17423
    matchRule moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:19780
    _callee$ moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:28295
    tryCatch moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17145
    makeInvokeMethod moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17233
    defineIteratorMethods moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17174
    asyncGeneratorStep moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17407
    _next moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17426
    promise callback*asyncGeneratorStep moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17416
    _next moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17426
    promise callback*asyncGeneratorStep moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17416
    _next moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17426
    asyncToGenerator_asyncToGenerator moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17431
    asyncToGenerator_asyncToGenerator moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17423
    init moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:28298
    _callee2$ moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:28298
    tryCatch moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17145
    makeInvokeMethod moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/ KISS Translator.user.js#12:17233
KISS Translator.user.js:19780:1269
源映射错误：Error: NetworkError when attempting to fetch resource.
源 URL：moz-extension://42ce36b5-ddd7-46a3-8557-e3af9b5203b3/%20KISS%20Translator.user.js#12
源映射 URL：browser-polyfill.js.map

</p>
</details>

**Comment by fuzy112** [comment]
It works after changing the value of `@inject-into` to `page` or `auto`.

**Comment by fishjar** [comment]
The [v1.6.0](https://github.com/fishjar/kiss-translator/releases/tag/v1.6.0) version has fixed the problem of firefox, you can try to update it.

**Comment by fuzy112** [comment]
It works after updating to v1.6.0.  Thanks!
