### ISSUE TITLE
翻译插件使用deepl翻译带链接引用的文字时，丢失链接引用

### ISSUE THREAD

**Issue by loyejaotdiqr47123** [fishjar/kiss-translator#159]
例如
![image](https://github.com/fishjar/kiss-translator/assets/102934154/beddfadf-fd46-4fea-8e45-9e39e181ddd8)

![image](https://github.com/fishjar/kiss-translator/assets/102934154/604f814d-e0bf-4749-a007-318508e84a6d)

**Comment by fishjar** [comment]
如果确实需要保留链接，可以在规则设置的保留元素选择器中填写`a`
