### ISSUE TITLE
视频 字幕实时翻译切换字幕的时候有延迟, 请问可否优化一下?

### ISSUE THREAD

**Issue by os9sur** [fishjar/kiss-translator#168]
比如像这种的, 当字幕快速切换时候, 会有明显延迟, 甚至没来得及显示出来翻译,就又切换到下一句字幕了.
对比了一下另一个工具: "沉浸式翻译" 就没有这个问题.
但是它没有划词翻译功能. 相比之下更喜欢您这个工具, 所以能否优化一下? 谢谢!

![2024-07-28_131339](https://github.com/user-attachments/assets/ffc9e36b-0f74-40ee-9015-83d69acc4f21)

**Comment by fishjar** [comment]
目前本插件对字幕翻译确实比较鸡肋：
1、尤其是作者没有上传字幕，由youtube自动翻译的字幕，可能会一句话断开来翻译。
2、你这种应该是作者上传了字幕，但翻译服务比较慢，导致来不及显示翻译结果。

之前也想过优化思路：
1、最好的方式是通过AI语音识别并翻译出来，但消耗大量计算机资源，引导用户本地部署AI服务也有技术门槛。
2、还有个折中的方案，就是下载字幕并翻译，可用，但效果不佳，因为官方字幕断句不是按自然的句子断开的。目前大部分字幕翻译插件都是这种方案。

但限于时间精力，以及折中的方案效果不佳，暂没有实施优化。

**Comment by fishjar** [comment]
猜测是我上面所说的第二种方案，预下载官方自动识别的字幕，然后做了断句方面的优化处理，再翻译。
当然作为商业化软件，也可以根播放频次对一些热门视频按照第一种AI方案预处理，后面的用户播放时随时调出字幕。
