### ISSUE TITLE
请问类似于这种的非英文网页的内容可否设置成默认不翻译?

### ISSUE THREAD

**Issue by os9sur** [fishjar/kiss-translator#169]
![2024-07-28_133510](https://github.com/user-attachments/assets/33abf7fd-8080-465c-bdf9-7729c1013c3f)

**Comment by fishjar** [comment]
这很可能是本地的语言检测错误导致的，建议在规则设置中开启`远程语言检测`

**Comment by fishjar** [comment]
除了基本设置这里，还有规则那里要设置（可能我应该把这两个设置放到一起）

![微信截图_20240730112131](https://github.com/user-attachments/assets/c6478b88-4856-4f06-b12a-c229b045e6b7)

**Comment by fishjar** [comment]
> 反复尝试了一下, 发现是只有在用油猴模式时才会出现这种问题,用插件模式就OK 了. 而且在上个 issue [168](https://github.com/fishjar/kiss-translator/issues/168) 好像也是这种语言检测的问题: 字幕本来是英语, 但是显示识别成了 阿拉伯语

油猴脚本完全没有本地语言识别的功能，插件版的有，但是有时也不准确，最准确的是启用远程识别，但是需要多发出一次网络请求，可能影响翻译速度
