### ISSUE TITLE
Alt+Q shortcut doesn't work on firefox/violentmonkey

### ISSUE THREAD

**Issue by fuzy112** [fishjar/kiss-translator#17]

**Comment by fishjar** [comment]
Greasy Monkey script cannot use shortcut keys, only the extension version can use shortcut keys 

- `Alt+Q` to enable translation 
- `Alt+C` to switch styles

**Comment by fuzy112** [comment]
Would you mind introducing this package https://violentmonkey.github.io/guide/keyboard-shortcuts/ ?  It allows to register a function as shortcut in userscripts.  It is provided by Violentmonkey teams but it also can be used with other script managers.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Gabe ***@***.***>
发送时间: Friday, September 1, 2023 11:24:12 PM
收件人: fishjar/kiss-translator ***@***.***>
抄送: Zhengyi ***@***.***>; Author ***@***.***>
主题: Re: [fishjar/kiss-translator] Alt+Q shortcut doesn't work on firefox/violentmonkey (Issue #17)


Greasy Monkey script cannot use shortcut keys, only the extension version can use shortcut keys

  *   Alt+Q to enable translation
  *   Alt+C to switch styles

―

**Comment by fishjar** [comment]
感谢您的提示，我会尝试一下的。

实际上我之前从未用过`violentmonkey`，我只是适配了 [Tampermonkey](https://www.tampermonkey.net/) 和 [Userscripts Safari](https://github.com/quoid/userscripts)

**Comment by fishjar** [comment]
Already added, shortcut keys will be supported in the next version.

https://github.com/fishjar/kiss-translator/commit/23eb92853ea3ae9bc21d5f79ca4082bcb5261b14

**Comment by fuzy112** [comment]
It works. Thanks!
