### ISSUE TITLE
请问能否加个设置, 关闭视频字幕翻译?

### ISSUE THREAD

**Issue by os9sur** [fishjar/kiss-translator#177]
字幕由于翻译延迟, 会导致原生字幕频繁上下"跳动",视觉使用上非常不方便, 
所以能否加个开关设置, 关闭一下? 谢谢!

**Comment by fishjar** [comment]
其实修改下规则即可，参考： https://github.com/fishjar/kiss-translator/issues/62

**Comment by Ayx03** [comment]
其实更好的解决方案是提前获取字幕，翻译并替换，像沉浸式翻译那样。另外字幕翻译好像在b站上不工作

**Comment by Ayx03** [comment]
> > 其实更好的解决方案是提前获取整个字幕，翻译并替换，像沉浸式翻译那样，这样可能因为提供了上下文翻译效果也会更好。另外字幕翻译好像在b站上不工作
> 
> #168 之前和作者聊过, 好像不太容易实现, 如果你有好的实现方法可以跟他聊聊

在另一个issue的评论里（https://github.com/fishjar/kiss-translator/issues/74#issuecomment-2499638144）提供了一种构建YouTube .srt字幕下载链接的方式（不过依赖第三方服务，找到了一个应该不依赖第三方服务的python库但是应该不能直接用在浏览器扩展里？），剩下要问题的就是怎么翻译整个字幕文件（不知道会不会超过一些API的长度上限）并让网站的播放器读取翻译后的文件了，我有时间再研究一下
