### ISSUE TITLE
On some webpages the popup position is wrong

### ISSUE THREAD

**Issue by fuzy112** [fishjar/kiss-translator#18]
For example, in this page https://www.boost.org/doc/libs/1_83_0/doc/html/boost_asio/using.html the popup position is `left: 231px; top: 4689.5px;` on my machine, which is outside of the window.

**Comment by fuzy112** [comment]
The position is calculated using `document.documentElement.clientHeight` and `document.documentElment.clientWidth`, which don't return correct values on that page.  Would you please consider change them to `window.innerHeight` and `window.innerWidth`?

**Comment by fishjar** [comment]
其实最早使用的是`window.innerHeight`和`window.innerWidth`，但是右边有滚动条的时候会几乎将按钮遮挡住，所以后来就修改成`document.documentElement.clientHeight `了，但当时没意识到`firefox`的计算方式和`chrome`存在差异。

经过考虑暂时还是改回 `window.innerHeight`和`window.innerWidth`算了，这应该是更常见的写法，虽然会受到滚动条的影响。

请更新至 [v1.6.1](https://github.com/fishjar/kiss-translator/releases/tag/v1.6.1)

-------------------------------

In fact, the first ones used were `window.innerHeight` and `window.innerWidth`, but when there was a scroll bar on the right, the button would almost be covered, so it was later changed to `document.documentElement.clientHeight`, but I didn't realize it at the time.The calculation method of `firefox` is different from that of `chrome`.

After consideration, it is better to change back to `window.innerHeight` and `window.innerWidth` for the time being. This should be a more common way of writing, although it will be affected by the scroll bar.

Please update to [v1.6.1](https://github.com/fishjar/kiss-translator/releases/tag/v1.6.1)
