### ISSUE TITLE
全局设置译文样式

### ISSUE THREAD

**Issue by XuNing2** [fishjar/kiss-translator#189]
你好，以前是可以全局设置译文样式和指定翻译服务提供商的，现在的更新为什么把这个特性给删掉了呢？每一个网页都要设置一下很不方便。

**Comment by CresLeaf** [comment]
Use the overwrite section under rule setting.

**Comment by Ayx03** [comment]
规则设置 -> 覆写订阅规则

基于 Chromium 的浏览器的规则设置地址是

`chrome-extension://bdiifdefkgmcblbcghdlonllpjhhjgof/options.html#/rules`

Firefox:

`moz-extension://bb7e59d1-6ca2-45fd-b3aa-42f2760cbb1f/options.html#/rules`

个人认为这个应该放在基本设置里，确实令人困惑，一直在设置之后点击保存规则还总是默认的下划虚线格式
