### ISSUE TITLE
可以接入Safari 浏览器里的翻译Api吗？

### ISSUE THREAD

**Issue by oeieo** [fishjar/kiss-translator#19]
怎么能爬到Safari的翻译Api？

**Comment by fishjar** [comment]
没有苹果电脑，暂时没办法了。所以你看safari的插件版也搁置了。。

**Comment by alphavvv** [comment]
> 没有苹果电脑，暂时没办法了。所以你看safari的插件版也搁置了。。

太可惜了...希望有机会能考虑safari插件
