### ISSUE TITLE
[Feature request]脚本多项优化建议 

### ISSUE THREAD

**Issue by leic4u** [fishjar/kiss-translator#2]
已试用油猴脚本，期待上架 GreasyFork 。提出以下几点优化，请开发者酌情考虑添加。感谢开发者为社区带来又一开源、好用的翻译项目。   

1. 图标支持贴边隐藏，参考：网页限制解除（改）  https://greasyfork.org/scripts/28497 
2. 将开启翻译、设置等操作，收入浏览器的 TamperMonkey 右键菜单中，参考：网页限制解除（改）  https://greasyfork.org/scripts/28497 
![image](https://github.com/fishjar/kiss-translator/assets/32786903/8d92867a-7e92-41ed-8337-0c9cf7ac67f9)
3. 设置菜单加入默认规则，每个规则可使用默认规则或自定义（因为默认是微软翻译接口，我想换谷歌的，得一个一个去点…  ）
4. 支持自定义高亮色。
5. 谷歌的搜索结果中，只翻译了标题，未翻译正文。建议在「`匹配网址： *`」的默认规则中，加入正文的识别：  `[data-sncf='1']`
- 添加前：
![image](https://github.com/fishjar/kiss-translator/assets/32786903/645508f5-9edc-4af0-b5ec-29fc2cc0d587)
- 添加后：  
![image](https://github.com/fishjar/kiss-translator/assets/32786903/32aeccd5-36b9-402a-ae45-78de3ab2fe9d)

**Comment by fishjar** [comment]
首先感谢你提供的建议，今后会根据不同优先级进行优化，目前会先解决一些影响使用的兼容性问题：
1、优先级会放后面一些
2、其实插件版也没有加入右键菜单，本意是不想把右键搞得太复杂，不过后面可以考虑加入
3、这一条可能需要你再详细说明一下，我不一定完全理解，意思是加个按钮点击自动加入规则？
4、优先级会放后面一些
5、针对不同网站的规则，我只是给出几个示例，让用户自己灵活适配，后期如有必要，考虑增加一些常见网站的规则

**Comment by leic4u** [comment]
> 3、这一条可能需要你再详细说明一下，我不一定完全理解，意思是加个按钮点击自动加入规则？

其实主要是针对「开启翻译」、「翻译服务」、「原文语言」、「目标语言」、「文字样式」这几个设置。就类似于一个全局设置，其他站点可以把这几项设置为采用全局设置。
有全局设置功能的话，如果我想把所有站点的默认翻译服务，都从微软翻译改为谷歌翻译的时候，只需要改全局设置一个地方。

你说的那个，我理解有点类似于 ublock origin 那种选择页面元素，自定义屏蔽规则的那个吧？如果能够做到这样，肯定是最棒的。

**Comment by fishjar** [comment]
> > 3、这一条可能需要你再详细说明一下，我不一定完全理解，意思是加个按钮点击自动加入规则？
> 
> 其实主要是针对「开启翻译」、「翻译服务」、「原文语言」、「目标语言」、「文字样式」这几个设置。就类似于一个全局设置，其他站点可以把这几项设置为采用全局设置。 有全局设置功能的话，如果我想把所有站点的默认翻译服务，都从微软翻译改为谷歌翻译的时候，只需要改全局设置一个地方。
> 
> 你说的那个，我理解有点类似于 ublock origin 那种选择页面元素，自定义屏蔽规则的那个吧？如果能够做到这样，肯定是最棒的。

大概明白了，意思是这几个下拉框全部增加一个 `采用全局` 的选项？这个提议看起来不错，已纳入优化计划。

**Comment by fishjar** [comment]
新版本：v1.3.7

> 1. 图标支持贴边隐藏...
已支持

> 2. 将开启翻译、设置等操作，收入浏览器的 TamperMonkey 右键菜单中...
暂不做

> 3. 设置菜单加入默认规则...
已添加 `*` 星号选项，表示采用全局设置

> 4. 支持自定义高亮色。
已支持

> 5. 谷歌的搜索结果中，只翻译了标题，未翻译正文。
已添加 `www.google.com` 规则 `h3, .IsZvec, [data-sncf="1"]`

**Comment by leic4u** [comment]
> 1. 图标支持贴边隐藏...
> 已支持

已测试，拖拽图标后会自动贴边，但未隐藏。
首次打开页面或刷新页面后，图标将回到右下角，未贴边，且未记忆上次拖拽位置，必须手动拖拽一下才可以重新贴边。
贴边后最好能设置一个非常低的透明度，以免对浏览页面产生干扰。

> 3. 设置菜单加入默认规则...
> 已添加 * 星号选项，表示采用全局设置

已测试，其他规则可以正常使用全局设置。

> 4. 支持自定义高亮色。
>已支持

已测试，使用 HEX 色值（如 #163e75 ）可正常修改高亮色。

> 已添加 `www.google.com` 规则 `h3, .IsZvec, [data-sncf="1"]`

规则好像没有更新到，设置页面还是原来的规则。

**Comment by fishjar** [comment]
> > 1. 图标支持贴边隐藏...
> >    已支持
> 
> 已测试，拖拽图标后会自动贴边，但未隐藏。 首次打开页面或刷新页面后，图标将回到右下角，未贴边，且未记忆上次拖拽位置，必须手动拖拽一下才可以重新贴边。 贴边后最好能设置一个非常低的透明度，以免对浏览页面产生干扰。

后期有时间再改进一下。

> > 已添加 `www.google.com` 规则 `h3, .IsZvec, [data-sncf="1"]`
> 
> 规则好像没有更新到，设置页面还是原来的规则。

- 插件点击重新载入按钮，而不是删除再安装
- 油猴脚本拖进去重新安装

这两种情况，原来的存储的设置/规则不会清空，也不会载入新的官方规则。并且`开启翻译`这个字段的数据类型改变了，沿用旧的规则文件，会导致一点小小bug。在考虑要不要加一个重置规则的按钮，或者加一个同步官方规则的按钮，不过目前我要先解决一下油猴脚本数据同步的问题。

**Comment by leic4u** [comment]
> > > 1. 图标支持贴边隐藏...
> > >    已支持
> > 
> > 
> > 已测试，拖拽图标后会自动贴边，但未隐藏。 首次打开页面或刷新页面后，图标将回到右下角，未贴边，且未记忆上次拖拽位置，必须手动拖拽一下才可以重新贴边。 贴边后最好能设置一个非常低的透明度，以免对浏览页面产生干扰。
> 
> 后期有时间再改进一下。

感谢开发者更新， 1.4.3 版支持自动贴边了，透明度也有一定程度的降低。似乎还是没能实现以下两点：
1. 新开/刷新页面，记忆上次拖拽的位置；
2. 透明度仍偏高，还是会干扰页面阅读，建议改为 0.05 。试了下，0.05 基本上不会干扰页面了。建议可以再隐藏多一点，现在我拖到左边试了下，现在隐藏了 28px ，我试了下 40px 其实也是可以的。

> > > 已添加 `www.google.com` 规则 `h3, .IsZvec, [data-sncf="1"]`
> > 
> > 
> > 规则好像没有更新到，设置页面还是原来的规则。
> 
> * 插件点击重新载入按钮，而不是删除再安装
> * 油猴脚本拖进去重新安装
> 
> 这两种情况，原来的存储的设置/规则不会清空，也不会载入新的官方规则。并且`开启翻译`这个字段的数据类型改变了，沿用旧的规则文件，会导致一点小小bug。在考虑要不要加一个重置规则的按钮，或者加一个同步官方规则的按钮，不过目前我要先解决一下油猴脚本数据同步的问题。

这个好像目前 1.4.3 版本还没解决，更新过来后，规则也还是没更新。

**Comment by fishjar** [comment]
> 1. 新开/刷新页面，记忆上次拖拽的位置；

是将位置保存在本地storage里面，还是需要不同客户端同步，不同客户端窗口大小不一样，同一个客户端窗口大小也可能变化，所以最终逻辑会有些复杂，可能需要再想想。

> 2. 透明度仍偏高，还是会干扰页面阅读，建议改为 0.05 。试了下，0.05 基本上不会干扰页面了。建议可以再隐藏多一点，现在我拖到左边试了下，现在隐藏了 28px ，我试了下 40px 其实也是可以的。

这个可以再优化一下，不过可能要区分电脑和手机端，手机上隐藏太多就很难点击到了。

> 这个好像目前 1.4.3 版本还没解决，更新过来后，规则也还是没更新。

我仔细想过这个问题，但目前还没有定好一个方案。

- 如果每次更新版本就更新本地规则，会把用户编辑过的规则替换掉，对于偷懒的人可能有用，但对于喜欢仔细编辑自己规则的人来说这是灾难。
- 如果增加一个 `同步规则` 按钮给偷懒的人用或许有点用。
- 增加 `同步规则` 也会引出一些问题：
  - 官方规则谁来维护，如何维护？
  - 官方规则无疑会越来越多，但用户真正需要的可能仅仅只是很小一部分，因为每个人经常访问的网址并不多。
- 但如果没有官方规则也不行，对于没有`CSS`知识的人可能就不够友好。

目前我在考虑的一个方案是，把规则分为`官方规则`和`用户规则`两部分，维护一个简短的官方规则，每次升级时更新或每天更新，并且官方规则不允许编辑。匹配规则的时候，优先匹配用户的规则。
  
如果你有更好的建议，欢迎提出。

**Comment by leic4u** [comment]
> 是将位置保存在本地storage里面，还是需要不同客户端同步，不同客户端窗口大小不一样，同一个客户端窗口大小也可能变化，所以最终逻辑会有些复杂，可能需要再想想。

感谢开发者。已经更新到 1.4.4 ，贴边隐藏功能在新开/刷新页面时，已可以记忆上次拖拽的位置。
默认位置在页面下方，没有被遮挡。我自行拖动到屏幕左侧后，感觉效果更好，是否可以考虑默认就在屏幕左侧？

> 目前我在考虑的一个方案是，把规则分为官方规则和用户规则两部分。

把规则分为两部分的方案我也认为不错。但我建议可以分为`订阅规则`和`用户规则`两个部分。
`订阅规则`实现默认内置规则的更新，`官方订阅`默认就订阅上，用户可以自建`第三方订阅`（其实就是一个链接），加入到订阅列表中。
后续有优秀的`第三方订阅`之后，除了默认订阅的`官方订阅`之外，甚至可以默认订阅一些优秀的`第三方订阅`。类似于 ublock origin 的规则订阅。如下：
![image](https://github.com/fishjar/kiss-translator/assets/32786903/c3263a3a-e0ea-4fc4-8493-138e3d902c23)
但这样需要确认下，两个甚至多个规则集合如果有冲突时，是取其中一个，还是取大家的并集。（建议可以用并集，最大化页面各个元素的翻译，反正现在本插件也有语言判断，已经可以避免掉不需要翻译的部分被翻译的情况）
这样不懂前端css的人，基本上不做任何修改，也可以正常使用。同时也能够方便有些前端大佬可以分享自己的一些规则出来，为本翻译插件加砖添瓦。

`用户规则`，也可以跟现在一样，支持用户自己输入一些零散的规则。（建议也用并集的方式）

**Comment by fishjar** [comment]
1、按钮的初始位置换到左边，问题不大。
2、最新的v1.4.5版，我已经将规则分成了`用户规则`和`内则规则`，并增加了`注入内置规则`的切换按钮。
3、再加一个`订阅规则`是个不错的想法，考虑增加这个功能。
4、规则冲突比较好解决，各种规则按优先级，合成一个有序数组，前面的匹配了，后面的就忽略。

**Comment by leic4u** [comment]
感谢开发者。该 issue 提出的功能请求已全部解决，现关闭该 issue 。后续`规则订阅`以及其他相关问题将另外提出 issue 来反馈和讨论。
