### ISSUE TITLE
部分网站无法分段翻译

### ISSUE THREAD

**Issue by leic4u** [fishjar/kiss-translator#20]
部分网站在自己添加规则后，无法分段翻译，只能整段翻译输出。

目前已知的有：
- https://www.phoronix.com/news/Google-Cloud-C3A-AmpereOne （选择器： .content ）
![image](https://github.com/fishjar/kiss-translator/assets/32786903/aace3b29-1305-488b-9d7a-2552a0bcfcbf)
- https://t.me/s/r_trackers  （选择器： .tgme_widget_message ）
![image](https://github.com/fishjar/kiss-translator/assets/32786903/45e4d988-0239-4cc1-af69-18ebb84d79ac)

**Comment by fishjar** [comment]
这个问题TG上也有人提出过，主要原因是这个网站的代码非常不规范，目前还没想到完美的办法。
如果是遇到`br`标签就当作断句，会带来一些副作用，因为常规网站`br`只是换行，并不是断句的意思。一个完整句子分开来翻译是不对的。

**Comment by fishjar** [comment]
我单独写了一个简单的脚本来应对此类网站，项目地址：https://github.com/fishjar/kiss-webfixer

至于为何不是集成在 `KISS Translator` 里面，因为我认为这类网站五花八门，需求又比较小众，针对它们特殊处理不应是我的重点，给出一个方案，独立出来交给社区自理反而比较好。

效果如下：
![Screenshot from 2023-09-04 11-47-42](https://github.com/fishjar/kiss-translator/assets/1157624/1762a068-4f17-4cb5-aab8-7ac56847c65d)

**Comment by leic4u** [comment]
> 我单独写了一个简单的脚本来应对此类网站，项目地址：https://github.com/fishjar/kiss-webfixer
> 
> 至于为何不是集成在 `KISS Translator` 里面，因为我认为这类网站五花八门，需求又比较小众，针对它们特殊处理不应是我的重点，给出一个方案，独立出来交给社区自理反而比较好。

电报这种呢，也是存在同样的问题，电报应该不算小众了。看是在补丁脚本里解决，还是集成到本项目里。
比如：https://t.me/s/r_trackers （选择器： .tgme_widget_message ）

**Comment by fishjar** [comment]
当然是写在修复脚本里了：https://github.com/fishjar/kiss-webfixer

- 这种网站虽然小众，但时不时遇到一个，脚本更新很快，插件发版还要审核。
- 比如这个你刚才发的 `t.me`，只用增加两行就解决了。

已经提交了：https://github.com/fishjar/kiss-webfixer/commit/c6a584862bdf1502f1a5414e00d0f14ab2c73ff4

看看效果：

![Screenshot from 2023-09-04 23-44-03](https://github.com/fishjar/kiss-translator/assets/1157624/ad577625-0666-43b1-9693-8fca2eacff90)

**Comment by leic4u** [comment]
我思考了一下，我个人觉得如果可以的话，还是集成的方式比较好一点。

因为对用户来说，需要的功能是同一个：即我需要对某网页进行翻译。
为了这一个需求，让用户需要安装一个插件+一个脚本（或两个脚本），对用户来说是一个负担。
（而且其他插件可能只安装一个即可的情况下，此问题会显得更加突出）

而且很可能很多小白用户（翻译插件面向的小白用户可能会更多），根本就不知道还需要安装另外一个脚本来解决这个问题。
他们可能安装完本插件，发现对某网站无效，直接就弃用了。

这其实对项目来说不是个好事，望考虑。

**Comment by fishjar** [comment]
你说的也有道理，习惯插件的用户可能不会再装一个脚本。

但引入一些小概率的特殊处理代码总觉得不优雅，再考虑考虑。

**Comment by fishjar** [comment]
> > 你说的也有道理，习惯插件的用户可能不会再装一个脚本。
> > 但引入一些小概率的特殊处理代码总觉得不优雅，再考虑考虑。
> 
> 有没有可能作为一个额外加载的功能模块，也以订阅方式来解决？

刚好我也想到这个方案

**Comment by fishjar** [comment]
修复脚本已经集成到最新的版本

**Comment by leic4u** [comment]
已测试，网页问题修复成功，已经可以正常分段翻译。
![image](https://github.com/fishjar/kiss-translator/assets/32786903/6d63e9fa-d6dd-4f01-a26f-488c47ff8209)

![image](https://github.com/fishjar/kiss-translator/assets/32786903/bf90803b-4215-43d2-8c17-37f147ecefd0)
