### ISSUE TITLE
部分网站出现正则表达式匹配错误

### ISSUE THREAD

**Issue by leic4u** [fishjar/kiss-translator#21]
![image](https://github.com/fishjar/kiss-translator/assets/32786903/ede71fec-5eda-437b-8127-b60d6496168c)

看起来好像是 `*` 这个出问题了？
其他有些网站也会出现这个问题，一直没管。今天在一个想翻译的网站发现这个有提示，使用快捷键无效，才发现好像是脚本的问题。

**Comment by fishjar** [comment]
能重现吗？我这里打开这个地址没发现错误

**Comment by fishjar** [comment]
等有时间我两个都装上看看什么问题。

**Comment by leic4u** [comment]
> 查到原因了，`auto_feed.user.js` 的问题。
> 
> 在该脚本生效的任意网站，打开控制台，执行：
> 
> ```js
> "".replaceAll("*","");
> ```
> 
> 这个脚本大量修改原型函数的定义，简直就是定时炸弹，非常危险，建议不要使用。

这个脚本对玩 PT 的人来说是刚需😂，可能不使用不太行。。。
我只能给开发者提下这个问题，看能否尽量解决下这个冲突。
