### ISSUE TITLE
Firefox 浏览器里默认快捷键 Alt+Q 无法使用

### ISSUE THREAD

**Issue by benzBrake** [fishjar/kiss-translator#22]
1.浏览器内容工具箱获取跟Q有关的快捷键：没有重复的。
```
> document.querySelectorAll(`[key="q"]`) 
NodeList [ key#key_quitApplication, key]
0: <key id="key_quitApplication" data-l10n-id="quit-app-shortcut" modifiers="accel,shift" command="cmd_quitApplication" reserved="true" key="Q">​
1: <key modifiers="accel,alt" key="Q" oncommand="//">
​
length: 2
<prototype>: NodeListPrototype { item: item(), keys: keys(), values: values(), … }
```
2.因为我使用的是 Floorp 是Firefox的一个第三方版本，为了排除干扰，我新下载了一个 nightly 版本，Alt+Q还是用不了
3.尝试在快捷键设置里设置为 Ctrl+Alt+Q 可以使用
![图片](https://github.com/fishjar/kiss-translator/assets/11323774/fcd261f6-88c7-4d99-95c3-5d7d835f41ba)
4.改为Ctrl+Alt+Q后尝试把快捷键改回 Alt+Q 改不回去了
附加信息：
插件版本：1.6.4

**Comment by fishjar** [comment]
是插件版的？有点奇怪，我这里是可以的，除非与其他插件的快捷键冲突了。

**Comment by benzBrake** [comment]
> 是插件版的？有点奇怪，我这里是可以的，除非与其他插件的快捷键，或者系统快捷键冲突了。

找了一下午 找到了，戴尔显示器管理程序占用的，但是找遍设置也没找到哪里设置了Alt+Q快捷键
