### ISSUE TITLE
[Feature Request]订阅规则的更新按钮旁，新增最近更新成功时间

### ISSUE THREAD

**Issue by leic4u** [fishjar/kiss-translator#23]
以便用户知道该订阅规则是哪个版本的，来判断自己是否需要手动再点一遍。

（顺带提一下，自动更新是逻辑是咋定的，我这里脚本版 1.6.7，好像自动更新订阅的功能没有生效）

**Comment by fishjar** [comment]
1、目前订阅规则没有单独记录每条规则的同步时间，但会记录自动更新的时间

3、自动更新是间隔一天以上时间

  - 插件版每次启动浏览器检查
  - 脚本版每次打开页面检查

 4、你的自动更新没有生效估计还是之前那个`auto_feed.user.js`脚本的影响（不过下个版本我的代码也会作出相应改动）

  - 控制台应该会看到`[sync subrule error]`的日志

**Comment by leic4u** [comment]
> 1、目前订阅规则没有单独记录每条规则的同步时间，但会记录自动更新的时间

那是不是可以提供一个展示给用户看的更新时间呢？主要诉求还是想知道自己这个订阅，是啥时候更新的，是不是最新的。

> 4、你的自动更新没有生效估计还是之前那个`auto_feed.user.js`脚本的影响（不过下个版本我的代码也会作出相应改动）
> 
> * 控制台应该会看到`[sync subrule error]`的日志

这个问题我提给 `auto_feed` 项目了，但那边作者说这边的代码阅读难度有点大，我看了下确实有点难读😂

**Comment by fishjar** [comment]
> > 1、目前订阅规则没有单独记录每条规则的同步时间，但会记录自动更新的时间
> 
> 那是不是可以提供一个展示给用户看的更新时间呢？主要诉求还是想知道自己这个订阅，是啥时候更新的，是不是最新的。
> 

这个没问题

> > 4、你的自动更新没有生效估计还是之前那个`auto_feed.user.js`脚本的影响（不过下个版本我的代码也会作出相应改动）
> > 
> > * 控制台应该会看到`[sync subrule error]`的日志
> 
> 这个问题我提给 `auto_feed` 项目了，但那边作者说这边的代码阅读难度有点大，我看了下确实有点难读😂

他们代码的问题在我之前的截图那里展示了，并且给出了重现的代码 

```js
"".replaceAll("*","");
```

**Comment by leic4u** [comment]
> 他们代码的问题在我之前的截图那里展示了，并且给出了重现的代码
> 
> ```js
> "".replaceAll("*","");
> ```

这个问题不在这里讨论了，插件版没有冲突，脚本冲突也只是部分小众 PT 站点，问题不大。

> > 那是不是可以提供一个展示给用户看的更新时间呢？主要诉求还是想知道自己这个订阅，是啥时候更新的，是不是最新的。
> 
> 这个没问题
> 

这个新特性加上了我就可以关闭这个 issue 了。

**Comment by fishjar** [comment]
最新版已显示同步时间

**Comment by leic4u** [comment]
感谢开发者
