### ISSUE TITLE
怎么自定义全局样式？

### ISSUE THREAD

**Issue by kidzgy** [fishjar/kiss-translator#26]
firefox117，扩展1.6.4
软件很好用，我遇到几个问题，想请教一下：

从工具栏上点的扩展，弹出菜单设置的样式是临时的，页面一刷新就无效了。

似乎没有办法设置全局样式，只能单个规则设置。能不能多增加单个规则默认跟随全局选项。

我看GF脚本都1.6.7了，火狐扩展更新会不会比脚本滞后？

还有就是，个人规则管理方面，没有多选、批量删除功能，不知道能不能增加这一块？

**Comment by fishjar** [comment]
> firefox117，扩展1.6.4 软件很好用，我遇到几个问题，想请教一下：
> 
> 从工具栏上点的扩展，弹出菜单设置的样式是临时的，页面一刷新就无效了。
> 

是的，弹出框都是临时的设置。

> 似乎没有办法设置全局样式，只能单个规则设置。能不能多增加单个规则默认跟随全局选项。
> 

全局样式在`个人规则`那里有个 `*` 星号的就是全局。
其他样式选择 "*" 就代表跟随全局。

> 我看GF脚本都1.6.7了，火狐扩展更新会不会比脚本滞后？
> 

目前因为版本更新比较频繁，扩展审核比较慢就会滞后。
以后更新慢了，滞后的情况就不常见。

> 还有就是，个人规则管理方面，没有多选、批量删除功能，不知道能不能增加这一块？

暂时会增加一个清空的按钮，多选的功能麻烦一点，后面再考虑加不加。

**Comment by kidzgy** [comment]
![微信截图_20230909122135](https://github.com/fishjar/kiss-translator/assets/6967810/26a24836-de65-44e4-83f7-de7f8e23808b)

导出、导入的按钮反了吧？

**Comment by fishjar** [comment]
> ![微信截图_20230909122135](https://user-images.githubusercontent.com/6967810/266760196-26a24836-de65-44e4-83f7-de7f8e23808b.png)
> 
> 导出、导入的图标反了吧？

上传朝上，下载朝下，应该没错

**Comment by kidzgy** [comment]
导入是导进去，所以要朝下，往里放，配置是导出来，所以朝上。
