### ISSUE TITLE
[feature request] 快速添加规则

### ISSUE THREAD

**Issue by jqtmviyu** [fishjar/kiss-translator#27]
能否像  SwitchyOmega 那样, 点击拓展多一个快速添加功能, 而不用进到设置界面
(删除修改才需要到设置)

**Comment by fishjar** [comment]
你是说增加一个快速添加按钮，设置选项都用默认的？

**Comment by kidzgy** [comment]
> 你是说增加一个快速添加按钮，设置选项都用默认的？

题主说的应该就是这个意思。
我顺着这个意思再补充一下，添加规则时，可以选择一级域名或二级域名，添加完后是默认启用全局的样式。至于更精确的匹配以及选择器就到设置页自定义精确调整。

**Comment by jqtmviyu** [comment]
> 你是说增加一个快速添加按钮，设置选项都用默认的？

<img width="182" alt="image" src="https://github.com/fishjar/kiss-translator/assets/19925192/8230de8c-62d7-4aa8-be17-9b24abfc5f72">

体验上来说当然是把 "变更项" 也一起保存更好. 
进一步的回填和删除倒没那么重要.

**Comment by kidzgy** [comment]
> > 你是说增加一个快速添加按钮，设置选项都用默认的？
> 
> <img alt="image" width="182" src="https://user-images.githubusercontent.com/19925192/266799831-8230de8c-62d7-4aa8-be17-9b24abfc5f72.png">
> 
> 体验上来说当然是把 "变更项" 也一起保存更好. 进一步的回填和删除倒没那么重要.

变更项最关键的是选择器，其他项基本上都可以跟随默认。假设你是当前网站页面弹出小窗口来编辑这个参数，那在打开F12用元素查看器时，界面交互似乎就不那么友好，弹出的小窗口很大可能会挡住元素选择，这时需要将小窗口挪来挪去。

当然了，如果秉持“我可以不用，但不能没有”的设计原则，可以给扩展或脚本菜单添加按钮，“添加当前网站”，点击后，弹出一个小窗，可以自定义网址（默认域名则是二级域名，如news.baidu.com），可以自定义选择器，可以是否开启翻译（这个作用有时候是用了订阅规则，默认开启了翻译，想要屏蔽翻译的时候方便添加）及翻译服务，至于原文语言、目标语言、文字样式我觉得可以不出现在小窗口。

**Comment by fishjar** [comment]
新版已支持快速添加
