### ISSUE TITLE
修改全局默认文字样式，对已创建的单条规则无效

### ISSUE THREAD

**Issue by kidzgy** [fishjar/kiss-translator#28]
FIREFOX117，暴力猴+脚本。

症状描述：
1、我先创建单条规则，并且自定义样式，该种样式是添加背景颜色，而不是下划线。
2、我修改全局规则*，自定义文字样式有下划线。
3、修改单条规则文字样式，由自定义样式改为*，这样的话就跟随全局样式。
4、清除缓存，刷新页面，用的样式还是之前创建的有背景颜色的。
5、只能通过删除规则，重新创建才能使全局样式生效。

![微信截图_20230908221131](https://github.com/fishjar/kiss-translator/assets/6967810/3a46a24a-3200-46d7-b648-2d4dec56e67e)
![微信截图_20230908221117](https://github.com/fishjar/kiss-translator/assets/6967810/4cbe34df-993f-4245-86ab-add059ec7fa9)
![11111](https://github.com/fishjar/kiss-translator/assets/6967810/2516bdb0-2af2-4305-aa68-713bf39c5d0f)

**Comment by kidzgy** [comment]
另外，能不能添加一个选项，可以屏蔽掉页面左边的“文A”翻译按钮？

**Comment by fishjar** [comment]
非常细心才能发现的bug！下个版本修复。

脚本版如果没有那个按钮，就没法打开弹窗操作，也不方便进入设置页面了啊。

**Comment by kidzgy** [comment]
可以从脚本选项那里打开的
![微信截图_20230908235537](https://github.com/fishjar/kiss-translator/assets/6967810/533cc88e-b6ee-47ca-9ebe-33d4fea8e5e8)
我觉得【Toggle Style】这个选项没什么用，只能虚线和模糊来回切换，谁会那么无聊临时改样式呢？要改也是从设置页面改。这个选项改为直接打开选项页比较妥当。不然的话，要先点第三个按钮，弹出窗口，再点一次按钮，才进入设置。每次进入设置要操作两次鼠标，非常麻烦。

其实按钮这种视觉性的，我都非常建议增加一个选项，自主选择是否屏蔽，毕竟我可以不用，但是不能没有。因为要翻译的页面也就寥寥几个外文网站，“文A”按钮一直悬挂在那里挺影响观感的。

**Comment by kidzgy** [comment]
对了，我发现，releases里的firefox zip是不支持直接安装的。
打个比方：https://github.com/violentmonkey/violentmonkey/releases 里下载zip文件，然后火狐打开附加组件管理器页面，将zip拖动到该页面中，是可以实现安装拓展的。但是作者的zip包不支持，哪怕解压出来，自己去掉firefox文件夹，重新打包，也安装不了。

其实作者维护这么多chrome edge firefox三个扩展再加脚本，会不会太累了，我觉得是不是主打脚本就行了？毕竟维护、更新会方便好多

**Comment by kidzgy** [comment]
![微信截图_20230909002017](https://github.com/fishjar/kiss-translator/assets/6967810/78fa6637-490c-4460-a1b9-c82f3c0cf7f2)

自定义快捷键不支持修改为空，一般来说修改快捷键时按退格键都是设置为空。

**Comment by fishjar** [comment]
> 可以从脚本选项那里打开的 ![微信截图_20230908235537](https://user-images.githubusercontent.com/6967810/266664953-533cc88e-b6ee-47ca-9ebe-33d4fea8e5e8.png) 我觉得【Toggle Style】这个选项没什么用，只能虚线和模糊来回切换，谁会那么无聊临时改样式呢？要改也是从设置页面改。这个选项改为直接打开选项页比较妥当。不然的话，要先点第三个按钮，弹出窗口，再点一次按钮，才进入设置。每次进入设置要操作两次鼠标，非常麻烦。
> 
> 其实按钮这种视觉性的，我都非常建议增加一个选项，自主选择是否屏蔽，毕竟我可以不用，但是不能没有。要翻译的页面也就寥寥几个外文网站，“文A”按钮一直悬挂在那里挺影响观感的。

对，可能有人习惯从脚本选项操作，可以考虑 增加隐藏按钮选项

**Comment by fishjar** [comment]
> 对了，我发现，releases里的firefox zip是不支持直接安装的。 打个比方：https://github.com/violentmonkey/violentmonkey/releases 里下载zip文件，然后火狐打开附加组件管理器页面，将zip拖动到该页面中，是可以实现安装的。但是作者的zip包不支持，哪怕解压出来，自己去掉firefox文件夹，重新打包，也安装不了。
> 
> 其实作者维护这么多chrome edge firefox三个扩展再加脚本，会不会太累了，我觉得是不是主打脚本就行了？毕竟维护、更新、兼容会方便好多

1、暂时未仔细研究这个问题，建议直接从插件市场安装。

2、其实主要是维护脚本版耗费更多时间，有多个浏览器+多个脚本管理器。后续更新预计不会那么频繁了。

**Comment by fishjar** [comment]
> ![微信截图_20230909002017](https://user-images.githubusercontent.com/6967810/266671828-78fa6637-490c-4460-a1b9-c82f3c0cf7f2.png)
> 
> 自定义快捷键不支持修改为空，一般来说修改快捷键时按退格键都是设置为空。值留空时，又变成默认快捷键了。

对，这个漏考虑了。下版修复

**Comment by kidzgy** [comment]
我发现用alt+Q 快捷键，仍然会回到之前绿色背景的样式，存在3种切换，不翻译、带下划线、带背景色。

**Comment by fishjar** [comment]
> 我发现用alt+Q 快捷键，仍然会回到之前绿色背景的样式，存在3种切换，不翻译、带下划线、带背景色。

我这里没有重现你说的问题，可以再多试试看

**Comment by kidzgy** [comment]
> > 我发现用alt+Q 快捷键，仍然会回到之前绿色背景的样式，存在3种切换，不翻译、带下划线、带背景色。
> 
> 我这里没有重现你说的问题，可以再多试试看

是我的问题，同时启用扩展和脚本了，测试的忘记将扩展禁用掉。
