### ISSUE TITLE
关于设置界面UI的建议

### ISSUE THREAD

**Issue by kidzgy** [fishjar/kiss-translator#29]
![微信截图_20230909002407222](https://github.com/fishjar/kiss-translator/assets/6967810/0a121a3e-92c3-4086-af5b-830b0b3913f2)
如图所示。

**Comment by fishjar** [comment]
首先感谢你的 建议，不过基本上暂时不会更改：

1、`个人规则` 下方本来是没有 `订阅规则`，因为有用户反映`注入订阅规则`不好理解，就改为只要启用了就显示出来。还有个作用是，添加规则的时候，其实有个过滤的功能，能够一屏展示相关的`个人规则`和`订阅规则`，帮助填写。

2、`*` 下个版本可以加一个`全局`的说明文字。不固定在首位，是因为全局规则优先级是最低的，并且全局规则因该不经常修改。

3、网址有长有短，还可以多个网址写在一起，所以可能会很长，但不能缩略显示，因为过滤的时候需要看到全部的网址才方便。而且分成左右栏显示的话，手机等小屏幕不友好。
