### ISSUE TITLE
[Request]Upload tampermonkey scripts to GreasyFork or some other platforms

### ISSUE THREAD

**Issue by showgood163** [fishjar/kiss-translator#3]
Upload tampermonkey scripts to [GreasyFork](https://greasyfork.org/) or some other platforms

**Comment by fishjar** [comment]
由于之前还在快速开发阶段，以及解决各种bug，代码更新频繁，也不想给一个半成品出去，所以所有平台都没上。
刚好今天所有已知问题（除了safari）解决的差不多了，所以刚才已经上传到 GreasyFork 了。

脚本地址：https://greasyfork.org/zh-CN/scripts/472840-kiss-translator-%E7%AE%80%E7%BA%A6%E7%BF%BB%E8%AF%91

**Comment by showgood163** [comment]
ok, then may update the readme of this repo for clarification.
