### ISSUE TITLE
[freture request]支持 webdav 同步

### ISSUE THREAD

**Issue by leic4u** [fishjar/kiss-translator#30]
自己部署一个 kiss-worker 还是太麻烦了，还需要自己有服务器。

希望能支持 webdav

**Comment by fishjar** [comment]
kiss-worker 基于 [Cloudflare](https://www.cloudflare.com/) 免费服务，不需要自己的服务器。应该是门槛最低了的。

**Comment by leic4u** [comment]
> kiss-worker 基于 [Cloudflare](https://www.cloudflare.com/) 免费服务，不需要自己的服务器。应该是门槛最低了的。

啊？那把 kiss-worker 克隆下来后是部署在本地电脑上一直运行一个服务嘛？我看又要 git clone 又要 deploy 啥的，还以为是运行在服务器上。
如果不是运行在服务器上，是不是也要求本地电脑上得安装 git 环境？

有点没搞懂这个 KV 是咋用的，kiss-worker 的文档也写得有点简单。看能否补充一下？

当然后续能支持 webdav 最好了，webdav 还是更加普遍一点。

**Comment by fishjar** [comment]
kiss-worker 要求：

- cloudflare帐号
- 本地安装git+nodejs

之前文档确实太简单了，而且是技术人员视角。等有时间我写个详细点的文档。
也许还需提供多一种备份方式的选择。

**Comment by leic4u** [comment]
webdav 的话，用户注册一个 Dropbox 或者坚果云就搞定了。
不喜欢用第三方储存服务的人，还可以自建 webdav（一般有这种想法的人多少还是有一点技术能力的，而且 webdav 网上教程也多）。

**Comment by fishjar** [comment]
新版已支持 webdav

**Comment by leic4u** [comment]
> 新版已支持 webdav

坚果云填入后同步失败，打开F12查看，发现我点击`立即同步`按钮后，没有发出任何请求。
![image](https://github.com/fishjar/kiss-translator/assets/32786903/cc76d7cb-6a9e-4b23-8b2a-ae92b0dd801a)

**Comment by fishjar** [comment]
> > 新版已支持 webdav
> 
> 脚本版，坚果云填入后同步失败，打开F12查看，发现我点击`立即同步`按钮后，没有发出任何请求。 ![image](https://user-images.githubusercontent.com/32786903/269804312-cc76d7cb-6a9e-4b23-8b2a-ae92b0dd801a.png)

我看你填写的接口地址不对，正确应是： https://dav.jianguoyun.com/dav/

**Comment by leic4u** [comment]
> 我看你填写的接口地址不对，正确应是： https://dav.jianguoyun.com/dav/

不是这个问题，使用 `https://dav.jianguoyun.com/dav/` 也是同步失败。（多了一个`/webdav/`的路径是因为我自己又建了一个叫`webdav`的文件夹而已。）
![image](https://github.com/fishjar/kiss-translator/assets/32786903/81c42871-2165-469b-b0c4-c06a6aaddd26)

**Comment by fishjar** [comment]
![Screenshot from 2023-09-22 15-01-06](https://github.com/fishjar/kiss-translator/assets/1157624/3279ea7c-f172-46bc-b89c-0395240f1163)

要到这个页面添加一个应用，密码不是账户的密码，而是应用的密码

**Comment by leic4u** [comment]
> 要到这个页面添加一个应用，密码不是账户的密码，而是应用的密码

这个我知道，我就是这样用的。而且我有其他应用早就已经用起来了。
![image](https://github.com/fishjar/kiss-translator/assets/32786903/b7301712-a642-460d-b648-24418c0cef58)

**Comment by leic4u** [comment]
刚刚试了一下插件版，可以同步成功，是脚本版的问题。

**Comment by fishjar** [comment]
那就奇怪了，我这里测试 chrome+Tampermonkey 脚本是可以同步的

插件版没有悬浮球，可以用快捷键 alt+k 弹窗

**Comment by fishjar** [comment]
我等会发个新版，当前版本点击设置快捷键有个严重bug，可能与此有关，也可能无关。

**Comment by leic4u** [comment]
> 插件版没有悬浮球，可以用快捷键 alt+k 弹窗

手机 kiwi 浏览器使用时，我个人感觉对悬浮球是刚需。

**Comment by leic4u** [comment]
> 那就奇怪了，我这里测试 chrome+Tampermonkey 脚本是可以同步的

我也是 Chrome + Tampermonkey + kiss-translator 这个配置，但就是同步不了。
我再删除脚本，把脚本全新安装一遍试试。

**Comment by leic4u** [comment]
> 我等会发个新版，当前版本点击设置快捷键有个严重bug，可能与此有关，也可能无关。

1.7.3 脚本版同步成功了。

**Comment by leic4u** [comment]
> 手机上确实悬浮按钮方便，后面考虑加一个在手机上

好的，那这个我单开一个 issue ，这里就不讨论悬浮球了。

**Comment by leic4u** [comment]
最新的 1.7.4 测试过，脚本版的 webdav 同步还是失败的哈。

**Comment by fishjar** [comment]
我多次测试均成功同步，没能重现。

你打开开发者面板有没有错误日志之类的。

**Comment by leic4u** [comment]
这个是点击同步时的网络请求：
![动画5](https://github.com/fishjar/kiss-translator/assets/32786903/f4abfbdd-61c1-4c8a-8acd-48e1fafa6747)

这个是控制台：
![image](https://github.com/fishjar/kiss-translator/assets/32786903/2dd406ab-3d43-4c41-b9cb-d45d9e06c08f)

**Comment by fishjar** [comment]
提示404，表示接口地址不对。改成 https://dav.jianguoyun.com/dav/ 再试试

**Comment by fishjar** [comment]
我这好像重现了问题，我再试试

**Comment by leic4u** [comment]
> 提示404，表示接口地址不对。改成 https://dav.jianguoyun.com/dav/ 再试试

这个接口也试过的，也不行。关键是同样的配置，插件版可以，脚本版不可以。那只能是脚本版的问题了。



> 我这好像重现了问题，我再试试

好的，我也想知道我这是为啥会出现这个问题。如果你复现了，可以跟我讲一下复现条件，我看我在刻意避开复现条件的情况下，是否可以正常同步。

**Comment by fishjar** [comment]
如果文件夹或文件原本不存在，就重现了。

这确实是一个bug，因为脚本版在判断404时提前抛出错误，实际应该交给webdav库继续处理。

等会发个新版本。

**Comment by fishjar** [comment]
试试新版 v1.7.5

**Comment by leic4u** [comment]
> 如果文件夹或文件原本不存在，就重现了。
> 
> 这确实是一个bug，因为脚本版在判断404时提前抛出错误，实际应该交给webdav库继续处理。

https://github.com/fishjar/kiss-translator/issues/30#issuecomment-1730973132

这个复现条件我在这里提了，看你没响应这个，还以为不是这个问题导致的。

v1.7.5 已测试，同步成功。感谢开发者修复此问题。🎉🎉🎉

**Comment by leic4u** [comment]
v1.7.14 又出现这个问题了。脚本版同步失败，插件版同步成功。
![image](https://github.com/fishjar/kiss-translator/assets/32786903/a1b3517f-6e01-4c13-b2be-b6ec05b08d46)

**Comment by fishjar** [comment]
没能重现，多试几次看看。
可以打开开发者面板看看详细的请求信息。

**Comment by leic4u** [comment]
跟上面这条评论 https://github.com/fishjar/kiss-translator/issues/30#issuecomment-1730657379 一样，没有看到任何请求。
![image](https://github.com/fishjar/kiss-translator/assets/32786903/c5ed972e-3db4-4175-8d73-d461c49fdebb)

**Comment by fishjar** [comment]
控制台的错误也看看

**Comment by leic4u** [comment]
![image](https://github.com/fishjar/kiss-translator/assets/32786903/28169b07-f026-466f-9241-c38d93e703cb)

**Comment by fishjar** [comment]
在脚本设置那里添加了黑名单？

**Comment by leic4u** [comment]
> 在脚本设置那里添加了黑名单？

我自己没动过脚本设置呢
![image](https://github.com/fishjar/kiss-translator/assets/32786903/1498c57d-b951-476f-8356-8c9d6595c226)

**Comment by fishjar** [comment]
这就比较奇怪了。
由于我这里没有复现，也很难去找到真正原因。

**Comment by leic4u** [comment]
> 这就比较奇怪了。 由于我这里没有复现，也很难去找到真正原因。

我今天还测试了是不是插件或脚本冲突导致的，然后我把所有除 Tampermonkey 外的所有插件禁用了，并且只开启 Kiss-translator 一个脚本，还是同步失败。我还把脚本彻底删除后，重新安装脚本，重新填了同步地址、账号、密钥，也同步失败。

确实不知道是为啥了。

已经抛弃脚本了，转用插件版本了。😂

问题我先关闭了，看后续有没有哪位小伙伴碰到相同问题再说吧。
