### ISSUE TITLE
可以接入POE服务的ChatGpt翻译吗？

### ISSUE THREAD

**Issue by oeieo** [fishjar/kiss-translator#31]
[类似chathub插件里边调用poe的chatgpt](https://github.com/chathub-dev/chathub)，因为openai实在是付不了钱，而且还会封ip，poe 就不会而且还免费

**Comment by fishjar** [comment]
等有空看看poe相关文档先

**Comment by oeieo** [comment]
> 等有空看看poe相关文档先

有文档吗？我没找到

**Comment by fishjar** [comment]
看了下，是没有，我之前还以为类似openai，提供官方接口文档。你发的那个项目也是利用类似爬虫技术接入的，如果是这样可能由另外的项目来实现比较合适。

**Comment by oeieo** [comment]
插件可以获取到网站的登录信息，直接调网站接口，其他项目不好获取登录信息

**Comment by fishjar** [comment]
可以另起项目，类似下面两个。然后接口包装成与openai数据结构一样就行了

https://github.com/mmdzov/poe-chat-api
https://github.com/ading2210/poe-api

**Comment by fishjar** [comment]
> 插件可以获取到网站的登录信息，直接调网站接口，其他项目不好获取登录信息

登录信息就是复制一下cookie，也不麻烦

**Comment by oeieo** [comment]
> 可以另起项目，类似下面两个。然后接口包装成与openai数据结构一样，或者符合自定义接口规范就行了
> 
> https://github.com/mmdzov/poe-chat-api https://github.com/ading2210/poe-api

我试了，不太好整，登录信息无法配置到代理项目中

**Comment by oeieo** [comment]
> > 插件可以获取到网站的登录信息，直接调网站接口，其他项目不好获取登录信息
> 
> 登录信息就是复制一下cookie，也不麻烦

好的，我瞅瞅

**Comment by oeieo** [comment]
看了，不方便，哈哈哈
