### ISSUE TITLE
[Bug report] 特定网站失效

### ISSUE THREAD

**Issue by toooonyy** [fishjar/kiss-translator#32]
Firefox 117.0.1 + Violentmonkeyv2.15.0
https://www.t-online.de/region/berlin/id_100245680/brandenburg-rechtsextreme-compact-tv-moderatorin-verliert-traumberuf-.html
脚本版无法在此页面工作，log都是这种无法插入错误 ``Uncaught DOMException: Node.insertBefore: Child to insert before is not a child of this node``。扩展版正常工作
<img width="732" alt="Screen Shot 2023-09-20 at 16 56 54" src="https://github.com/fishjar/kiss-translator/assets/3480434/77ed52c7-4611-46f2-9817-c67041a39779">

不知道这是这个网页不规范的问题或者是脚本的问题。

**Comment by fishjar** [comment]
油猴脚本版确实存在一些冲突，等有空再研究下，不一定能解决，建议优先使用浏览器扩展版本

**Comment by fishjar** [comment]
新版已修复
