### ISSUE TITLE
 freture request: 支持自定义「翻译」快捷键

### ISSUE THREAD

**Issue by everyx** [fishjar/kiss-translator#33]
目前没找到自定义快捷键的方法，有的网站和 Alt + Q 的快捷键有冲突，比如 Reddit，希望能加入自定义的功能

**Comment by fishjar** [comment]
油猴脚本自定义快捷键在设置页面。
浏览器扩展版本在扩展管理那里，比如chrome在这个页面：chrome://extensions/shortcuts

**Comment by everyx** [comment]
哈哈，找到了，谢谢
