### ISSUE TITLE
[feature request]插件版添加悬浮球

### ISSUE THREAD

**Issue by leic4u** [fishjar/kiss-translator#34]
目前手机浏览器使用插件版时，不方便使用快捷键和其他方式弹窗设置。
脚本版的悬浮球非常适合手机浏览器操作，建议在插件版也能支持悬浮球，并且支持在设置中管理是否隐藏悬浮球。

**Comment by fishjar** [comment]
新版已添加。

可以在设置页面选择显示还是隐藏，此设置随设备，不会同步。

**Comment by leic4u** [comment]
收到，感谢开发者响应需求
