### ISSUE TITLE
Firefox 中启用「鼠标悬停翻译」后会导致翻译功能失效

### ISSUE THREAD

**Issue by everyx** [fishjar/kiss-translator#35]
设置之后，悬停之后也不会翻译，并且按 Alt + A (我自定义的翻译快捷键) 也不能翻译，将「鼠标悬停翻译」功能禁用后就正常了

**Comment by fishjar** [comment]
未能重现你说的问题。

- 开启`鼠标悬停翻译`后，翻译开关（`alt+q`）仍然启作用，必须打开（alt+k查看是否打开），鼠标悬停才会翻译。
- 如果选择了`组合键+鼠标悬停`，必须先按住`组合键`，再将鼠标移到文本才会翻译。如果先移过去，再按`组合键`则不会翻译。

**Comment by everyx** [comment]
> 未能重现你说的问题。
> 
>     * 开启`鼠标悬停翻译`后，翻译开关（`alt+q`）仍然启作用，必须打开（alt+k查看是否打开），鼠标悬停才会翻译。
> 
>     * 如果选择了`组合键+鼠标悬停`，必须先按住`组合键`，再将鼠标移到文本才会翻译。如果先移过去，再按`组合键`则不会翻译。

😂 抱歉，是我理解错了，我以为是单开就默认有悬停翻译（不需要按翻译开关），实际上是打开之后需要仍需要按翻译开关，只是翻译的范围不是整个页面了
