### ISSUE TITLE
希望能增加划词翻译

### ISSUE THREAD

**Issue by copperdong** [fishjar/kiss-translator#36]
因为有些网页某些部分，鼠标悬停翻译不了，谢谢

**Comment by fishjar** [comment]
1、鼠标悬停翻译不了或许是选择器的写法问题，更新一下规则或许就可以了。
2、目前已经有很多划词翻译类的插件了，包括我也有开发了一个自用的。
3、划词翻译的重点其实是单词的查询，与整句对照翻译是很好的互补，但短时间内没有合并计划。

**Comment by fishjar** [comment]
最新版已增加简单的划词翻译功能：

![Screenshot from 2023-10-25 15-14-38](https://github.com/fishjar/kiss-translator/assets/1157624/7c2743bb-b22e-4e06-80a7-a5373c48d4b7)
