### ISSUE TITLE
[Bug report] 网站样式异常

### ISSUE THREAD

**Issue by BIMiracle** [fishjar/kiss-translator#37]
1.7.5
浏览器扩展程序
打开 [https://store.epicgames.com/zh-CN/](https://store.epicgames.com/zh-CN/)
这个链接时会导致样式异常，两台电脑都是这样，禁用扩展程序后正常
Google Chrome 117.0.5938.150
![image](https://github.com/fishjar/kiss-translator/assets/18730979/037d1f75-d902-4438-99be-9eddecbc3583)

**Comment by fishjar** [comment]
悬浮按钮使用了`Material UI`引发的问题，打开 https://mui.com/ 也是一样的问题。
目前扩展版可以通过隐藏悬浮按钮解决，脚本版则暂无办法。

**Comment by fishjar** [comment]
这个bug已解决，将在下个版本修复
