### ISSUE TITLE
[Bug report] 使用DeepL翻译过长的文本段时会显示原文而非译文

### ISSUE THREAD

**Issue by Minaduki-Shigure** [fishjar/kiss-translator#40]
Edge 118.0.2088.46 + KISS Translator v1.7.7 （在之前的版本和iOS Userscript上也有同样的问题）

在使用DeepL API翻译较长的文本时，会出现译文区域为原文（且可能会被截断）而非译文的现象，使用其他的API不会出现这样的问题。

比如如下页面的Introduction的第一段文本：https://theory.stanford.edu/~nikolaj/programmingz3.html

下图为使用DeepL API的翻译结果：
<img width="527" alt="image" src="https://github.com/fishjar/kiss-translator/assets/32758828/b7c993de-1626-4d47-a307-3ed6f903038e">

下图为使用Google和Microsoft的翻译结果：
<img width="525" alt="image" src="https://github.com/fishjar/kiss-translator/assets/32758828/93720126-c22e-413f-8b50-c5787990a8d8">
<img width="525" alt="image" src="https://github.com/fishjar/kiss-translator/assets/32758828/0fec09e8-c10d-4533-96bf-515af78871ac">

我尝试查找了DeepL API的手册，但是没有找到DeepL是否对免费API的文段长度有所限制，直接调用API对同样的文段进行翻译的结果是正常的，如下图：
<img width="791" alt="image" src="https://github.com/fishjar/kiss-translator/assets/32758828/472ac7a5-b729-4594-92f0-d2a45c00d137">

我并不太确定是否确实是因为文本段长度导致的，但是确实比较短的文本段没有出现过这样的问题。

**Comment by fishjar** [comment]
我没有DeepL帐号，所以没法测试这个问题。你能否打开插件的`开发者工具`看看实际的请求情况？
（如果看不到请求，需要先在设置页面清除缓存）

![Screenshot from 2023-10-16 09-56-02](https://github.com/fishjar/kiss-translator/assets/1157624/0b56fb27-7ce6-4f2a-8f69-4dc43bb7297f)

**Comment by Minaduki-Shigure** [comment]
我用开发者工具检查请求后，发现KISS Translator在请求DeepL API的时候，包含了一个我没有考虑过的参数`split_sentences`且其值设置为0，按照[DeepL API手册](https://www.deepl.com/docs-api/translate-text/translate-text)的说法，这个参数告诉DeepL是否应当将输入的文本进行分句处理，如果不设置，默认会按照标点符号和换行分割，如果设置为0，则不会分割，会将输入作为一整句处理。

> Sets whether the translation engine should first split the input into sentences. For text translations where tag_handling is not set to html, the default value is 1, meaning the engine splits on punctuation and on newlines.

> Possible values are:
> 0 - no splitting at all, whole input is treated as one sentence
1 (default when tag_handling is not set to html) - splits on punctuation and on newlines
nonewlines (default when tag_handling=html) - splits on punctuation only, ignoring newlines
For applications that send one sentence per text parameter, we recommend setting split_sentences to 0, in order to prevent the engine from splitting the sentence unintentionally.

在Postman中添加参数`split_sentences=0`，可以复现问题：
![image](https://github.com/fishjar/kiss-translator/assets/32758828/2276d6c8-5b65-426a-beb9-7bfe6320b601)

如果设置参数`split_sentences=1`或者干脆不设置，则可以得到正确的翻译结果。
![image](https://github.com/fishjar/kiss-translator/assets/32758828/5a7c7613-8e9a-4e5e-b143-60f0d6c95200)
![image](https://github.com/fishjar/kiss-translator/assets/32758828/7b695164-bc7a-47c6-b7b9-961680db723c)

可能是因为将过长的段落作为一句输入会超过DeepL模型的限制，导致其不能正确翻译。

我尝试注释了`src/apis/index.js`文件中第135行的`split_sentences: "0",`并重新编译了插件，修改后的插件的翻译结果是正确的：
![image](https://github.com/fishjar/kiss-translator/assets/32758828/51b66a82-defd-40c3-b432-4dff8d7e6667)

供您参考。

**Comment by fishjar** [comment]
这个文档我在写代码的时候也看了，特意设置为字符串`0`，就是为了避免分割句子，因为我不确定分割后，DeepL是否会丢失上下文的信息来进行翻译。

DeepL要求请求body不能超过128 KiB，可能触发了这个上限，但是如果是这样的话，允许分割句子也是同样超过大小。

不管如何，注释135这一行没问题就暂时按这个方案用着吧。
