### ISSUE TITLE
能否做到像沉浸翻译那样，鼠标悬停段落后翻译

### ISSUE THREAD

**Issue by toyo2333** [fishjar/kiss-translator#43]
不想整篇翻译，因为浪费token或者因为你翻译后排版混乱，或者因为有时候只阅读一部分再决定是否继续阅读。

所以需要这个功能。

**Comment by fishjar** [comment]
这个功能已经支持了，在设置页面开启

**Comment by toyo2333** [comment]
> 这个功能已经支持了，在设置页面开启

我试了很多次，没效果，悬停后按shift（我设置的），什么翻译都没有。

只选鼠标悬停就正常，选shift+鼠标悬停 就无效。

**Comment by fishjar** [comment]
> > 这个功能已经支持了，在设置页面开启
> 
> 我试了很多次，没效果，悬停后按shift（我设置的），什么翻译都没有。
> 
> 只选鼠标悬停就正常，选shift+鼠标悬停 就无效。

- 开启鼠标悬停翻译后，翻译开关（alt+q）仍然启作用，必须打开（alt+k查看是否打开），鼠标悬停才会翻译。
- 如果选择了组合键+鼠标悬停，**必须先按住组合键，再将鼠标移到文本才会翻译**。如果先移过去，再按组合键则不会翻译。

**Comment by toyo2333** [comment]
> > > 这个功能已经支持了，在设置页面开启
> > 
> > 
> > 我试了很多次，没效果，悬停后按shift（我设置的），什么翻译都没有。
> > 只选鼠标悬停就正常，选shift+鼠标悬停 就无效。
> 
> * 开启鼠标悬停翻译后，翻译开关（alt+q）仍然启作用，必须打开（alt+k查看是否打开），鼠标悬停才会翻译。
> * 如果选择了组合键+鼠标悬停，**必须先按住组合键，再将鼠标移到文本才会翻译**。如果先移过去，再按组合键则不会翻译。

可以了，但这个逻辑对我来说很别扭。通常我是先决定翻译哪一段（鼠标移过去)，再按shift触发翻译。你现在这个逻辑，我需要额外注意鼠标的位置和处理。

**Comment by toyo2333** [comment]
> > > > 这个功能已经支持了，在设置页面开启
> > > 
> > > 
> > > 我试了很多次，没效果，悬停后按shift（我设置的），什么翻译都没有。
> > > 只选鼠标悬停就正常，选shift+鼠标悬停 就无效。
> > 
> > 
> > 
> > * 开启鼠标悬停翻译后，翻译开关（alt+q）仍然启作用，必须打开（alt+k查看是否打开），鼠标悬停才会翻译。
> > * 如果选择了组合键+鼠标悬停，**必须先按住组合键，再将鼠标移到文本才会翻译**。如果先移过去，再按组合键则不会翻译。
> 
> 可以了，但这个逻辑对我来说很别扭。通常我是先决定翻译哪一段（鼠标移过去)，再按shift触发翻译。你现在这个逻辑，我需要额外注意鼠标的位置和处理。

或者我得一直按住shift，然后向下一段移动鼠标。。这就更别扭了

**Comment by fishjar** [comment]
组合操作是有个顺序的问题，后面可以改进一下。

**Comment by toyo2333** [comment]
> 组合操作是有个顺序的问题，后面可以改进一下，以符合多数人习惯。

谢谢回复。还有就是翻译出来的段落展示排版可以再优化一些。现在是紧贴原段落。这个可以向沉浸式学习下。

其他方面都不错。都完善后 我差不多就可以迁移过来了。

**Comment by fishjar** [comment]
> > 组合操作是有个顺序的问题，后面可以改进一下，以符合多数人习惯。
> 
> 谢谢回复。还有就是翻译出来的段落展示排版可以再优化一些。现在是紧贴原段落。这个可以向沉浸式学习下。
> 
> 其他方面都不错。都完善后 我差不多就可以迁移过来了。

译文支持自定义样式，理论上可以改成你想要的样子，不过需要css知识

**Comment by fishjar** [comment]
最新版已对鼠标悬停做了优化，可以测试一下。

**Comment by toyo2333** [comment]
> 最新版已对鼠标悬停翻译做了优化，组合键不管是先按还是后按，应该都能翻译了，可以测试一下。

好的，等上架商店后更新

**Comment by toyo2333** [comment]
> 最新版已对鼠标悬停翻译做了优化，组合键不管是先按还是后按，应该都能翻译了，可以测试一下。

已测试，改动有效，复合我的预期。谢谢！

已经不用沉浸了。目前切换到这个基本都很好。后面打算用你的自部署同步服务。满意，再次感谢。

后续，我还是建议你做一下排版优化。为什么呢？

1、是使用者的感受，2、是产品推广的需求，我第一次知道这类软件，就是因为有人把双语对照翻译的效果截图发出来。然后大家去问这是什么翻译软件。这里，如果你的排版很别扭。比如译文紧贴原文段落。那么就不那么好看。分享和传播的效果就会打折扣。

再次感谢作者，提供真正开源的产品。

**Comment by toyo2333** [comment]
提个改进点鼠标悬停翻译 这篇文章的里面的小标题的时候，识别不是太准，必须要鼠标悬停在小标题上再适当上移，才可以翻译。否则翻译不了。

https://www.newyorker.com/humor/daily-shouts/how-to-save-the-bees

**Comment by toyo2333** [comment]
> > > 最新版已对鼠标悬停翻译做了优化，组合键不管是先按还是后按，应该都能翻译了，可以测试一下。
> 
> > 
> 
> > 已测试，改动有效，复合我的预期。谢谢！
> 
> > 
> 
> > 已经不用沉浸了。目前切换到这个基本都很好。后面打算用你的自部署同步服务。满意，再次感谢。
> 
> > 
> 
> > 后续，我还是建议你做一下排版优化。为什么呢？
> 
> > 
> 
> > 1、是使用者的感受，2、是产品推广的需求，我第一次知道这类软件，就是因为有人把双语对照翻译的效果截图发出来。然后大家去问这是什么翻译软件。这里，如果你的排版很别扭。比如译文紧贴原文段落。那么就不那么好看。分享和传播的效果就会打折扣。
> 
> > 
> 
> > 再次感谢作者，提供真正开源的产品。
> 
> 
> 
> 1、感谢您的建议：
> 
> 2、关于译文的排版美观问题，见仁见智，没有统一标准。所以可以通过自定义样式，去实现自己想要的排版。
> 
> 
> 
> 比如这段CSS：
> 
> 
> 
> ```css
> 
> color: #666;
> 
> background: linear-gradient(
> 
>   45deg,
> 
>   LightGreen 20%,
> 
>   LightPink 20% 40%,
> 
>   LightSalmon 40% 60%,
> 
>   LightSeaGreen 60% 80%,
> 
>   LightSkyBlue 80%
> 
> );
> 
> display: block;
> 
> border-left: 10px solid red;
> 
> padding: 10px;
> 
> &:hover {
> 
>   color: #333;
> 
> };
> 
> ```
> 
> 
> 
> 效果如下：
> 
> 
> 
> ![Screenshot from 2023-11-05 16-37-13](https://github.com/fishjar/kiss-translator/assets/1157624/ba02e44f-e783-498a-94cd-51643242af6f)
> 
> 
> 
> 

额，这个对我来说有些超纲了哈哈。我不是搞技术工作的。只会部署一些需要的工具提高效率。

**Comment by fishjar** [comment]
> > 最新版已对鼠标悬停翻译做了优化，组合键不管是先按还是后按，应该都能翻译了，可以测试一下。
> 
> 已测试，改动有效，复合我的预期。谢谢！
> 
> 已经不用沉浸了。目前切换到这个基本都很好。后面打算用你的自部署同步服务。满意，再次感谢。
> 
> 后续，我还是建议你做一下排版优化。为什么呢？
> 
> 1、是使用者的感受，2、是产品推广的需求，我第一次知道这类软件，就是因为有人把双语对照翻译的效果截图发出来。然后大家去问这是什么翻译软件。这里，如果你的排版很别扭。比如译文紧贴原文段落。那么就不那么好看。分享和传播的效果就会打折扣。
> 
> 再次感谢作者，提供真正开源的产品。

1、感谢您的建议：
2、关于译文的排版美观问题，见仁见智，没有统一标准。所以可以通过自定义样式，去实现自己想要的排版。

比如这段CSS：

```css
color: #666;
background: linear-gradient(
  45deg,
  LightGreen 20%,
  LightPink 20% 40%,
  LightSalmon 40% 60%,
  LightSeaGreen 60% 80%,
  LightSkyBlue 80%
);
display: block;
border-left: 10px solid red;
padding: 10px;
&:hover {
  color: #333;
};
```

效果如下：

![Screenshot from 2023-11-05 16-37-13](https://github.com/fishjar/kiss-translator/assets/1157624/ba02e44f-e783-498a-94cd-51643242af6f)

**Comment by fishjar** [comment]
> 提个改进点鼠标悬停翻译 这篇文章的里面的小标题的时候，识别不是太准，必须要鼠标悬停在小标题上再适当上移，才可以翻译。否则翻译不了。
> 
> https://www.newyorker.com/humor/daily-shouts/how-to-save-the-bees

试了下，这里的副标题确实需要偏上一点点，我目前还不知道怎么回事。

**Comment by toyo2333** [comment]
> > 提个改进点鼠标悬停翻译 这篇文章的里面的小标题的时候，识别不是太准，必须要鼠标悬停在小标题上再适当上移，才可以翻译。否则翻译不了。
> > https://www.newyorker.com/humor/daily-shouts/how-to-save-the-bees
> 
> 试了下，这里的副标题确实需要偏上一点点，我目前还不知道怎么回事。

还有这个：https://www.ft.com/content/90477190-32c1-4ca5-9ca3-6604e6f3ff62

FT上所有文章的标题。很难翻译，有时候要鼠标浮动找好多位置，才能翻译。麻烦你看看能否优化下。

**Comment by fishjar** [comment]
> > > 提个改进点鼠标悬停翻译 这篇文章的里面的小标题的时候，识别不是太准，必须要鼠标悬停在小标题上再适当上移，才可以翻译。否则翻译不了。
> > > https://www.newyorker.com/humor/daily-shouts/how-to-save-the-bees
> > 
> > 
> > 试了下，这里的副标题确实需要偏上一点点，我目前还不知道怎么回事。
> 
> 还有这个：https://www.ft.com/content/90477190-32c1-4ca5-9ca3-6604e6f3ff62
> 
> FT上所有文章的标题。很难翻译，有时候要鼠标浮动找好多位置，才能翻译。麻烦你看看能否优化下。

找到原因了，下个版本将修复此问题。

**Comment by toyo2333** [comment]
> > > > 提个改进点鼠标悬停翻译 这篇文章的里面的小标题的时候，识别不是太准，必须要鼠标悬停在小标题上再适当上移，才可以翻译。否则翻译不了。
> > > > https://www.newyorker.com/humor/daily-shouts/how-to-save-the-bees
> > > 
> > > 
> > > 试了下，这里的副标题确实需要偏上一点点，我目前还不知道怎么回事。
> > 
> > 
> > 还有这个：https://www.ft.com/content/90477190-32c1-4ca5-9ca3-6604e6f3ff62
> > FT上所有文章的标题。很难翻译，有时候要鼠标浮动找好多位置，才能翻译。麻烦你看看能否优化下。
> 
> 找到原因了，下个版本将修复此问题。

我看商店页面以及由1.7.12了，但我chrome里的1.7.11始终无法更新。点了更新也更新不了。是什么原因呢？是不是你触发更新的版本号写错了？

**Comment by fishjar** [comment]
> > > > > 提个改进点鼠标悬停翻译 这篇文章的里面的小标题的时候，识别不是太准，必须要鼠标悬停在小标题上再适当上移，才可以翻译。否则翻译不了。
> > > > > https://www.newyorker.com/humor/daily-shouts/how-to-save-the-bees
> > > > 
> > > > 
> > > > 试了下，这里的副标题确实需要偏上一点点，我目前还不知道怎么回事。
> > > 
> > > 
> > > 还有这个：https://www.ft.com/content/90477190-32c1-4ca5-9ca3-6604e6f3ff62
> > > FT上所有文章的标题。很难翻译，有时候要鼠标浮动找好多位置，才能翻译。麻烦你看看能否优化下。
> > 
> > 
> > 找到原因了，下个版本将修复此问题。
> 
> 我看商店页面以及由1.7.12了，但我chrome里的1.7.11始终无法更新。点了更新也更新不了。是什么原因呢？是不是你触发更新的版本号写错了？

没发现你说的问题。你可以删除再安装试试。

**Comment by toyo2333** [comment]
> > > > > > 提个改进点鼠标悬停翻译 这篇文章的里面的小标题的时候，识别不是太准，必须要鼠标悬停在小标题上再适当上移，才可以翻译。否则翻译不了。
> > > > > > https://www.newyorker.com/humor/daily-shouts/how-to-save-the-bees
> > > > > 
> > > > > 
> > > > > 试了下，这里的副标题确实需要偏上一点点，我目前还不知道怎么回事。
> > > > 
> > > > 
> > > > 还有这个：https://www.ft.com/content/90477190-32c1-4ca5-9ca3-6604e6f3ff62
> > > > FT上所有文章的标题。很难翻译，有时候要鼠标浮动找好多位置，才能翻译。麻烦你看看能否优化下。
> > > 
> > > 
> > > 找到原因了，下个版本将修复此问题。
> > 
> > 
> > 我看商店页面以及由1.7.12了，但我chrome里的1.7.11始终无法更新。点了更新也更新不了。是什么原因呢？是不是你触发更新的版本号写错了？
> 
> 没发现你说的问题。你可以删除再安装试试。

安装了最新版，这篇文字的悬停还是有问题
https://www.newyorker.com/magazine/2023/11/27/yesterday-a-new-history-of-nostalgia-tobias-becker-book-review

副标题斜体字那一段

**Comment by fishjar** [comment]
> 安装了最新版，这篇文字的悬停还是有问题 https://www.newyorker.com/magazine/2023/11/27/yesterday-a-new-history-of-nostalgia-tobias-becker-book-review
> 
> 副标题斜体字那一段

选择器没有覆盖到这个副标题的原因，需要添加相应的选择器。

**Comment by KnIfER** [comment]
这么麻烦，有必要么。我双击右键触发段落翻译，简直降维打击~
