### ISSUE TITLE
打开 Swift 文档页面抖动

### ISSUE THREAD

**Issue by zealotCE** [fishjar/kiss-translator#44]
浏览器：ARC Brower Version 1.13.1 (42579) / Chromium Engine Version 118.0.5993.88
系统：MacOS 14.1

对应URL： https://docs.swift.org/swift-book/documentation/the-swift-programming-language/aboutswift

具体情况：

https://github.com/fishjar/kiss-translator/assets/26129403/2e89f422-94e6-480e-a4cd-8c0f10f7abaf

**Comment by fishjar** [comment]
这个菜单的代码与翻译插件同时监听并动态更新，导致死循环了。

我的建议是，暂时不要翻译这个菜单。

**Comment by zealotCE** [comment]
好的

**Comment by fishjar** [comment]
我发现把`换行字符数`设置长一点，避免译文换行，这个菜单就不会抖动了。

**Comment by zealotCE** [comment]
换行字符数么？
我改成40个之后，确实是不抖了。
