### ISSUE TITLE
在使用openai的api接口时，即使api网址与sk都正确，但仍然提示出错

### ISSUE THREAD

**Issue by wgll000** [fishjar/kiss-translator#45]
站点https://aigptx.top/，已测试可联通

模型：gpt-3.5-turbo-16k-0613和gpt4都测试过，仍然无法连接

报错信息如下：测试失败: response:

望处理

**Comment by fishjar** [comment]
我没有相关的帐号测试，你能否按F12再点击测试，看看详细的请求信息。

PS：不过发现`接口测试`展示的错误信息太简单了，需要改一下。

**Comment by wgll000** [comment]
hi，我尝试在我的主力浏览器firefox上抓取消息但无法抓取，于是便更换为edge再次抓取
![image](https://github.com/fishjar/kiss-translator/assets/87935282/1853de12-042b-4733-a507-6c492e4a4ffb)
![image](https://github.com/fishjar/kiss-translator/assets/87935282/4837d205-ed30-4c05-8b5c-862cf79ef192)
![image](https://github.com/fishjar/kiss-translator/assets/87935282/2dfa92fe-e5f9-497b-bea9-bda7fbc05b82)
![image](https://github.com/fishjar/kiss-translator/assets/87935282/fa56b4a5-6150-4181-946d-97830cbaa251)
我没有相关的开发经验，如果有需求请告诉我该如何更改

**Comment by fishjar** [comment]
你的api网址也可能填写不完整，正确应是：

```sh
https://api.ohmygpt.com/v1/chat/completions
```

![Screenshot from 2023-11-05 09-43-00](https://github.com/fishjar/kiss-translator/assets/1157624/1387f075-5a31-4a4a-ad80-9869e7a2114a)

**Comment by wgll000** [comment]
> 你的api网址可能填写不完整，正确应是：
> 
> ```shell
> https://cn2us02.opapi.win/v1/complete
> ```
> 
> ![Screenshot from 2023-11-05 09-49-17](https://user-images.githubusercontent.com/1157624/280501440-f32f74aa-340f-41c0-8711-3d92efdf8663.png)

感谢，我通过https://api.ohmygpt.com/v1/chat/completions这个网址通过了测试
