### ISSUE TITLE
在多显示屏的情况下，浏览器默认缩放状态下，插件会出现鬼畜一般的放大与缩小

### ISSUE THREAD

**Issue by wgll000** [fishjar/kiss-translator#46]
![image](https://github.com/fishjar/kiss-translator/assets/87935282/d0cc4d46-0cd0-4cc6-847f-b84845aa6c46)
本人在使用windows10下的firefox119.0时，出现插件不正确缩放

**Comment by fishjar** [comment]
1、这个问发现已久，不过还没有找到完美解决方案，目前是通过注入修复补丁解决的。
2、百度搜索已经做过修复，可能是你没有打开`注入修复补丁`这个选项。
