### ISSUE TITLE
[Bug report]一些显示问题

### ISSUE THREAD

**Issue by h304192** [fishjar/kiss-translator#47]
1.划词翻译按钮不会跟随页面滚动

2.划词翻译按钮的显示位置似乎是鼠标松开时的位置

3.从选择文本时的起点一直到鼠标松开时的位置，在这个范围内点击任何位置翻译按钮都不会消失，以及输入框中删除选中的文本翻译按钮也不会消失

4.有些地方翻译会跑到最下面，这会导致看起来很乱  [有问题的页面](https://greasyfork.org/zh-CN/scripts/386925-youtube-ad-cleaner-include-non-skippable-ads-works)
![screenshot20231110 (7)](https://github.com/fishjar/kiss-translator/assets/109783518/0df3e981-3aea-439d-880a-2ffa37e0715e)

**Comment by fishjar** [comment]
> 1.划词翻译按钮不会跟随页面滚动
> 
> 2.划词翻译按钮的显示位置似乎是鼠标松开时的位置
> 

按钮的位置是鼠标松开的位置，并加上一定偏移量，偏移量可以在设置页面设置。

至于是是否跟随页面滚动，位置基于`鼠标`还是`选中的文字`，我觉得每个人习惯不同，且对使用影响不大，就选择了简单的做法。

> 3.从选择文本时的起点一直到鼠标松开时的位置，在这个范围内点击任何位置翻译按钮都不会消失，以及输入框中删除选中的文本翻译按钮也不会消失
> 
这其实是两个问题：
点击选中的文字，按钮不会消失，因为鼠标松开时，文字仍在选中状态，我将加上一点延迟来修复此问题。
输入框的内容删除后按钮也不消失，是因为仅监听鼠标松开事件，没有监听键盘事件。如果同时监听键盘事件，比如按`crl+a`，可能出现没法设定钮位置的情况。

> 4.有些地方翻译会跑到最下面，这会导致看起来很乱 [有问题的页面](https://greasyfork.org/zh-CN/scripts/386925-youtube-ad-cleaner-include-non-skippable-ads-works) ![screenshot20231110 (7)](https://user-images.githubusercontent.com/109783518/282002665-0df3e981-3aea-439d-880a-2ffa37e0715e.png)

这个很乱的原因是页面的内容不规范，可通过注入修复补丁来解决，不过目前修复补丁是订阅的方式，不能自定义添加，不是很方便，后面会考虑如何改进一下。

**Comment by h304192** [comment]
> 至于是是否跟随页面滚动，位置基于`鼠标`还是`选中的文字`，我觉得每个人习惯不同，且对使用影响不大，就选择了简单的做法。

确实每个人的习惯会有所不同，但是按钮如果不能跟随页面滚动的话会影响浏览体验，尤其是对图片来说

然后就是建议输入框不需要划词翻译，毕竟是自己写的内容

**Comment by fishjar** [comment]
新版可以自行增加`webfix`的规则：

![Screenshot from 2023-11-17 11-46-52](https://github.com/fishjar/kiss-translator/assets/1157624/33815f39-a901-424f-a1dc-36de3622cb7d)

然后翻译 [页面](https://greasyfork.org/zh-CN/scripts/386925-youtube-ad-cleaner-include-non-skippable-ads-works) 效果如下：

![Screenshot from 2023-11-17 11-45-02](https://github.com/fishjar/kiss-translator/assets/1157624/6ebbd1b6-f953-4922-9243-dcd64ad01f20)
