### ISSUE TITLE
扩展版希望添加右键菜单选项

### ISSUE THREAD

**Issue by kayanouriko** [fishjar/kiss-translator#48]
对我来说, 右键菜单开启翻译的各种操作是最不需要记忆的成本.
希望右键菜单能集成整页翻译, 划词翻译, 输入框翻译和打开设置四个功能, 其中整页翻译做成点击一下状态取反.
这样的做话, 对于支持规则的整页翻译功能, 我基本不用点击扩展图标来打开设置, 这样扩展图标可以隐藏起来, 但可以从右键菜单控制最常用的状态取反功能, 而不需要点击扩展图标里面再关闭. 
对于划词翻译, 我有需求, 但也不是高频的, 集成到右键菜单后可以隐藏掉悬浮窗, 减少日常使用页面上图标的干扰行为.
我看了一下 #2 里面是有提到这项优化的, 希望作者可以重新考虑一下这个需求, 还是有人会用的.

**Comment by fishjar** [comment]
1、下个版本增加右键菜单吧。
2、其实电脑操作的话，键盘快捷键也很方便。

**Comment by kayanouriko** [comment]
感谢, 对我来说翻译算是日常中较为低频的操作, 组合键不常使用也容易忘记.
右键菜单既不需要记忆成本又能集中功能选项操作是很好的解决方法了_(:3

**Comment by benzBrake** [comment]
我也喜欢右键菜单，主要是以前的翻译扩展都是右键翻译
