### ISSUE TITLE
划词翻译功能无法使用

### ISSUE THREAD

**Issue by laipz8200** [fishjar/kiss-translator#49]
v1.7.12时就存在问题，v1.7.13依然存在，

错误提示为 `s is undefined`

![image](https://github.com/fishjar/kiss-translator/assets/16485841/394ffe4c-86dc-421e-a8c4-d8d78fa03908)

**Comment by laipz8200** [comment]
补充一下测试平台：Linux/Firefox, macOS/Firefox, macOS/Chrome

**Comment by fishjar** [comment]
我在linux/chrome，linux/firefox均未重现你说的问题。
1、你安装的是浏览器扩展还是油猴脚本？
2、如果是油猴脚本，可能是与其他脚本冲突了。
3、可以打开开发者工具看看有没有更详细的错误信息。

**Comment by laipz8200** [comment]
> 我在linux/chrome，linux/firefox均未重现你说的问题。 1、你安装的是浏览器扩展还是油猴脚本？ 2、如果是油猴脚本，可能是与其他脚本冲突了。 3、可以打开开发者工具看看有没有更详细的错误信息。

感谢建议，安装的是浏览器扩展，使用Chrome在开发者模式下也没有观察到错误信息，不过卸载并重新安装后功能恢复正常了……
