### ISSUE TITLE
部分英文段落较多的页面，会导致页面和浏览器卡死

### ISSUE THREAD

**Issue by leic4u** [fishjar/kiss-translator#5]
首次进入部分英文段落较多的页面，会导致页面卡死，严重时浏览器也会卡死，看起来像是因为同时发起的翻译请求太多造成的。
等待加载完成后，再次进入页面就不会卡了，似乎是因为有缓存的缘故。
`crx 1.4.3`版本和`js 1.4.5`版本都测了，都存在这个问题。

测试地址：
1. https://github.com/Dreamacro/clash/releases 
2. https://github.com/alist-org/alist/releases 

测试了下划词翻译，它翻译很快，几乎一秒就出结果了，也不会卡死，不过就不知道它是咋实现的。

**Comment by leic4u** [comment]
奇怪，这个页面的英文段落也非常多，但却没有卡死。虽然翻译结果没有秒出，但基本上还是可以接受的速度。

https://github.com/JingMatrix/ChromeXt

这样看来，似乎段落较多并不是造成页面和浏览器卡死的原因，可能在 release 页面上有其他影响翻译进程的对象？

**Comment by fishjar** [comment]
我这里没有重现你说的问题，都是很快的。
你可以修改设置里面的请求并发数和间隔时间试试。

**Comment by leic4u** [comment]
> 我这里没有重现你说的问题，都是很快的。
> 你可以修改设置里面的请求并发数和间隔时间试试。

好的，我晚上回去把其他脚本作为测试变量一起试试，也可能是和其他哪个脚本发生冲突了啥的。
请问下如何清除翻译结果的缓存呢？能清除的话，我就使用一个页面反复测试了。

**Comment by fishjar** [comment]
> > 我这里没有重现你说的问题，都是很快的。
> > 你可以修改设置里面的请求并发数和间隔时间试试。
> 
> 好的，我晚上回去把其他脚本作为测试变量一起试试，也可能是和其他哪个脚本发生冲突了啥的。 请问下如何清除翻译结果的缓存呢？能清除的话，我就使用一个页面反复测试了。

1、确实存在优化提升的地方，但明显卡的情况我没有遇到过，不过我还是会看看如何优化一下。
2、目前插件版的可以选择重启时清除缓存，脚本版的按F12，打开开发者面板，找到`Application > Cache Storage`的地方，右键删除。后面可能会加个按钮方便清除缓存。

**Comment by leic4u** [comment]
我这晚上回来测试，也复现失败了。
用下午出现卡死现象的笔记本，和家里的台式，都没有出现卡的情况。

> 后面可能会加个按钮方便清除缓存。

感谢开发者如此重视反馈。❤️
但这个 Feat 我个人觉得不是很有必要，缓存清不清其实影响不大，一般情况下除了专门做测试，应该也不会有人专门去清缓存，几乎没有啥应用场景。
所以这个点可以不用专门解决哈。不过如果你觉得这个加上不费事，顺手而为，那也可以按你的思路来。🤝

这个 issue 我就先关掉了哈，后续如果再出现的话，我再来测试一下是什么原因导致的。

**Comment by leic4u** [comment]
![image](https://github.com/fishjar/kiss-translator/assets/32786903/0b9404b3-2de6-406a-93ec-cc474f517654)
在笔记本上复现了，台式电脑上还是没有复现，不知道是不是因为台式电脑性能更好一点的原因。

1. 在无痕模式下，只保留 SwitchyOmega Tampermonkey ublockOrigin 等几个必备拓展，关闭 Tampermonkey 中其他所有脚本，也会出现这个问题。
2. 将请求数改为 `5` ，请求间隔改为 `1000` ，仍然会出现，而且由于请求间隔变长，导致卡的时间变得更长了。
3. 关闭 Chrome 其他标签页，只保留 1 个测试地址（如 https://github.com/Dreamacro/clash/releases ）的标签页，也会出现。

复现的条件是：
1. 开机后正常使用一段时间 Chrome 。
2. 在测试地址中，快速往下滑，这时页面上会出现很多翻译加载的 icon 。（这一条似乎不是必要条件，有时不往下滑，或者缓慢往下滑也会卡）

这个性能问题稍微有点影响使用，但目前可以通过重启 Chrome 浏览器来临时解决。

**Comment by fishjar** [comment]
1、你说的卡是指浏览器页面卡，上下滑不顺畅？还是指翻译卡住，长时间显示加载icon？
2、按你的那个设置，翻译速度会很慢，我解释下那两个参数的具体含义：
 
- `间隔时间` 指每个请求排队的间隔时间，这个对翻译速度影响最大，设1000，就表示每1秒钟才翻译一条信息
- `请求数量` 指正在请求的最大数量，比如设为5，意思是如果有5个请求发出去但还没收到回应，就不会发出新的请求，即使间隔时间已经到了。如果网速很快，基本每次请求都能在设定的`间隔时间`内完成，那这个设置就可以忽略了。
- 一般`间隔时间`可以小一点，100以下，甚至是0，这样可以快速发出翻译请求，然后 `请求数量` 也小一点，10以内，用来防止突发的大量请求同时发出。

**Comment by leic4u** [comment]
> 1、你说的卡是指浏览器页面卡，上下滑不顺畅？还是指翻译卡住，长时间显示加载icon？

是电脑会卡顿，移动鼠标都会掉帧那种。

浏览器也会出现无响应的情况，类似下面这种，只是没有弹窗一般就响应过来了，然后马上又卡住。
![image](https://github.com/fishjar/kiss-translator/assets/32786903/29eff5fb-d314-4a36-a0d9-1c9cb0cfb68c)

页面上的翻译加载 icon 也会一直卡住，直到响应过来了，才开始逐个显示翻译结果。

应该不会是标签页开多了的原因，因为我专门测试了只有 1 个标签页的情况，也会出现卡顿。

用电脑用了一天，专门想做测试反而复现不了了，尴尬。。。先关了，下次能复现了再开。。。
