### ISSUE TITLE
[feature request]指定语言内容不翻译的选项

### ISSUE THREAD

**Issue by syazyz** [fishjar/kiss-translator#51]
在youtube这种多语言平台上，同一页面诸如法语西班牙语之类的评论需要翻译，但有些语言的内容（比如英语）我因为经常使用所以能看懂。这种情况下再翻译这些本来能看懂的语言就显得很破坏布局，也影响观看体验。可否加入一个指定语言不翻译的选项？

**Comment by fishjar** [comment]
这个配置是只需要在某些页面生效？还是做一个全局配置即可？

**Comment by syazyz** [comment]
> 这个配置是只需要在某些页面生效？还是做一个全局配置即可？

理想的情况最好是对域名等条件适配生效，因为可能只有不多的几个网站需要（比如上述的youtube）

**Comment by fishjar** [comment]
考虑非高频功能，已增加全局设置：不翻译的语言列表。
