### ISSUE TITLE
[feature request]对于kiss-translator功能的几个建议

### ISSUE THREAD

**Issue by lakevilladom** [fishjar/kiss-translator#52]
![image](https://github.com/fishjar/kiss-translator/assets/22128667/ba27ca5f-2738-4294-bdb9-cc6313842156)
1、如上图，两个功能基本相似，都是调用出来翻译框。建议合并成一个快捷键，选中文本情况下会弹出翻译框并自动翻译选中内容，没有选中文本情况下直接弹出翻译框；
2、另外对于从浏览器以外的地方已经复制内容到剪切板，然后调用翻译框手动粘贴翻译的时候不是特别便捷，希望可以优化；
3、希望翻译文字样式预置immersivetranslate中的“引用样式”；
4、对比immersivetranslate，有些地方翻译不完整，建议鼓励大家反馈翻译不完整的地方，加以优化

总之,kiss-translator非常优秀，开始准备弃用immersivetranslate，希望kiss-translator越来越好

**Comment by fishjar** [comment]
> ![image](https://private-user-images.githubusercontent.com/22128667/285718398-ba27ca5f-2738-4294-bdb9-cc6313842156.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwNzIxMjYsIm5iZiI6MTcwMTA3MTgyNiwicGF0aCI6Ii8yMjEyODY2Ny8yODU3MTgzOTgtYmEyN2NhNWYtMjczOC00Mjk0LWJkYjktY2M2MzEzODQyMTU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDA3NTcwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlOTdjNzViMWIxZWQ3MDdjMTlkNDdjNTBlMDk2MTczYzljMWYxZWI5MzIxMzE5YjUxMzJmNzJlYzYwOTdjMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Cv9AZ2F0RSc3N1cA3BQbcoEafSVT_oaS8b9mamuOAAM) 
> 1、如上图，两个功能基本相似，都是调用出来翻译框。建议合并成一个快捷键，选中文本情况下会弹出翻译框并自动翻译选中内容，没有选中文本情况下直接弹出翻译框； 

这里是可以共用一个快捷方式的，不过有些逻辑还没想好，比如选中文本时要不要关闭弹窗。

> 2、另外对于从浏览器以外的地方已经复制内容到剪切板，然后调用翻译框手动粘贴翻译的时候不是特别便捷，希望可以优化； 

在考虑：没有选中文本的情况下，要不要自动翻译粘帖板的文本，还是说加一个粘帖按钮。

> 3、希望翻译文字样式预置immersivetranslate中的“引用样式”； 

这个没问题。

> 4、对比immersivetranslate，有些地方翻译不完整，建议鼓励大家反馈翻译不完整的地方，加以优化

翻译是否完整跟规则设置有关，每个人的需求也不大一致。
当然，如果对规则有增补的需求，欢迎到这里提交issue或pr：https://github.com/fishjar/kiss-rules/issues

**Comment by fishjar** [comment]
1、快捷键已合并
2、已增加引用样式
