### ISSUE TITLE
[feature request]打开本地HTML或MHTML时也可以翻译

### ISSUE THREAD

**Issue by senlin-1573** [fishjar/kiss-translator#53]
打开本地HTML或MHTML时不能翻译
![image](https://github.com/fishjar/kiss-translator/assets/81969795/cddf7212-b2d1-4211-b3e8-4ff0d315bfa3)
希望能添加打开本地HTML或MHTML时也可以翻译的功能

**Comment by fishjar** [comment]
按理是不分本地，只要浏览器打开，一样能翻译。你是用什么浏览器？扩展还是油猴脚本？
