### ISSUE TITLE
翻译文字和样式的灰度问题

### ISSUE THREAD

**Issue by pipashu** [fishjar/kiss-translator#54]
翻译文字和样式的灰度，现在默认是加了灰度，如何调整灰度或者去掉灰度，谢谢。

**Comment by pipashu** [comment]
> > 翻译文字和样式的灰度，现在默认是加了灰度，如何调整灰度或者去掉灰度，谢谢。
> 
> ![image](https://private-user-images.githubusercontent.com/81969795/287421926-54d52553-0e1e-47d3-9dc5-90b6f67b92db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1MTU2MDIsIm5iZiI6MTcwMTUxNTMwMiwicGF0aCI6Ii84MTk2OTc5NS8yODc0MjE5MjYtNTRkNTI1NTMtMGUxZS00N2QzLTlkYzUtOTBiNmY2N2I5MmRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAyVDExMDgyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExMGZmYjJhYjcyOGEwYjY5ZmYzOTI0ZWQxZjIzZGEzOGUwZjI2MjQzYzU2NjUwOTFkM2M1ZWVhMGEwZTI5MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aKHogAgiqAT-yf1btVAsOzjVlr_48TTGr_Bopf0OaUw) 可以设置你喜欢字体的颜色

感谢回复。

**Comment by wsyzzz** [comment]
分享一个自用版本，去除了灰度，font-famliy需要有霞雾屏幕阅读版字体，可以根据喜好自定义
`font-family: "LXGW WenKai GB Screen R", Robot, SimSun, sans-serif;
font-size: 16px;
line-height: 1.6;
letter-spacing: 1px;
rgb(124, 204, 156);
color: rgb(0,0, 0);

/*下划线*/
  text-decoration-line: underline;
  text-decoration-style: dotted;
  text-decoration-color: #ff374f;
  text-decoration-thickness: 2px;
  text-underline-offset: 0.3em;
  -webkit-text-decoration-line: underline;
  -webkit-text-decoration-style: dotted;
  -webkit-text-decoration-color: #ff374f;
  -webkit-text-decoration-thickness: 2px;
  -webkit-text-underline-offset: 0.3em;
`
