### ISSUE TITLE
悬浮按钮点击翻译操作繁琐

### ISSUE THREAD

**Issue by h304192** [fishjar/kiss-translator#57]
希望能使悬浮按钮单击翻译，光标指向悬浮按钮时展开显示其他功能

**Comment by fishjar** [comment]
常用功能都有快捷键支持了，暂不计划将悬浮按钮复杂化。

**Comment by lakevilladom** [comment]
> 常用功能都有快捷键支持了，暂不计划将悬浮按钮复杂化。

应该可以设置是否显示悬浮按钮，因为我用快捷键，这个悬浮按钮是不是还有点干扰

**Comment by fishjar** [comment]
> > 常用功能都有快捷键支持了，暂不计划将悬浮按钮复杂化。
> 
> 应该可以设置是否显示悬浮按钮，因为我用快捷键，这个悬浮按钮是不是还有点干扰

目前版本已经可以设置隐藏翻译按钮

**Comment by lakevilladom** [comment]
> 悬浮

确实，刚发现
