### ISSUE TITLE
[Bug report]划词翻译跟随光标点击位置

### ISSUE THREAD

**Issue by h304192** [fishjar/kiss-translator#58]
YouTube观看视频时如果在选中文本的情况下，点击视频时划词翻译的悬浮按钮会显示在点击的位置

**Comment by fishjar** [comment]
本来设计就是这样的，选中文本，鼠标点击后，翻译按钮就跟随在鼠标的位置，方便点击翻译。
之前试过翻译按钮在选中文本的结尾或上面，感觉更不方便。

如果觉得按钮影响视觉，可以在设中隐藏翻译按钮，用快捷键或右键菜单来翻译选中文本。
