### ISSUE TITLE
reddit网站不翻译

### ISSUE THREAD

**Issue by senlin-1573** [fishjar/kiss-translator#59]

**Comment by fishjar** [comment]
这应该是规则问题，所有页面吗？我看正文是有翻译的，或者你发个没翻译的链接看看

**Comment by fishjar** [comment]
> > 这应该是规则问题，所有页面吗？我看正文是有翻译的，或者你发个没翻译的链接看看
> 
> 是规则问题，这个规则可以很好翻译reddit，div:is(.tbIApBd2DM_drfZQJjIum, ._1zPvgKHteTOub9dKkvrOl4),h1,h2,h3,h4,p,button 订阅规则那个不对，可以更新下。

可以到这里提交 PR 修正一下： https://github.com/fishjar/kiss-rules
