### ISSUE TITLE
改进含有非文本子节点的节点翻译

### ISSUE THREAD

**Issue by Long0x0** [fishjar/kiss-translator#61]
含有非文本子节点的节点翻译质量不佳，能否改进一下？
比如wikipedia里带公式的段落：https://en.wikipedia.org/wiki/Ordinary_least_squares
初步的思路是用占位符替换，翻译之后再替换回去：
```js
function translateText(text) {
  let translatedText = text; // use translate api here ...
  return translatedText;
}

function translateNode(node) {
  text = '';
  placeholders = [];

  // replace non-text children with placeholder ##N##
  for (let child of node.childNodes) {
    switch (child.nodeType) {
      case Node.TEXT_NODE:
        text += child.textContent;
        break;
      case Node.ELEMENT_NODE:
        text += ` ##${placeholders.length}## `;
        placeholders.push(child);
        break;
      default:
        break;
    }
  }

  // translate and replace back
  let translatedText = translateText(text);
  let translatedNode = document.createElement('translated-node');
  let parts = translatedText.split(/##(\d+)##/);
  for (let i = 0; i < parts.length; i++) {
    let part = parts[i];
    if (i % 2) {
      let index = parseInt(part, 10);
      if (index >= 0 && index < placeholders.length) {
        translatedNode.appendChild(placeholders[index].cloneNode(true));
      }
    } else {
      translatedNode.appendChild(document.createTextNode(part));
    }
  }
  return translatedNode;
}
```

**Comment by fishjar** [comment]
你这个想法存在几个问题：
1、要翻译的节点可能存在多层嵌套，子节点可能含有文本是需要翻译的。
2、翻译接口不一定能正确保留 `## ... ##` 这样的占位符。
3、即便能行，计算量大大增加。

**Comment by fishjar** [comment]
我发现翻译接口基本能原样返回类似`#(\d+)#`的占位符，所以新版已经作出了改进。
规则设置那里增加了一个`保留元素选择器`，给予用户更灵活的选择权。

大部分页面可能是：`code, img, svg`，
但 [这个页面](https://en.wikipedia.org/wiki/Ordinary_least_squares) 填： `.mwe-math-element`，

效果如下：

![Screenshot from 2024-01-04 16-51-51](https://github.com/fishjar/kiss-translator/assets/1157624/836a0db6-294d-42b0-be71-6b65a4b8c309)

**Comment by Long0x0** [comment]
效果很好了
我使用的选择器：
`pre, code, [translate='no'], .no-translate, .notranslate, .texhtml, .MathJax, .tex, .katex, .hljs, .CodeMirror, .code_responsive, .CodeBlock, .monospaced, .math, .formula, .mwe-math-element`

**Comment by fishjar** [comment]
新版已实现
