### ISSUE TITLE
能否对于字幕翻译设一个开关

### ISSUE THREAD

**Issue by pipashu** [fishjar/kiss-translator#62]
一般都用字幕扩展，功能强大，简约翻译的翻译会逾期产生重复叠加。

**Comment by fishjar** [comment]
添加一条个人规则，将订阅的`www.youtube.com`规则覆盖即可：

```css
h1, #video-title, #content-text, #title, yt-attributed-string>span>span
```

**Comment by pipashu** [comment]
> 添加一条个人规则，将订阅的`www.youtube.com`规则覆盖即可：
> 
> ```css
> h1, #video-title, #content-text, #title, yt-attributed-string>span>span
> ```

谢谢，设置效果成功。
