### ISSUE TITLE
报告一个推特格式无法翻译

### ISSUE THREAD

**Issue by pipashu** [fishjar/kiss-translator#63]
[insane](https://twitter.com/ulala_go/status/1732630359441838266)
类似这种推文格式，画红框部分没激发翻译，而“沉浸式翻译”可以正常工作。
![SCR-20231208-jqyj](https://github.com/fishjar/kiss-translator/assets/27265628/d304c54d-bc20-4093-8ea8-b9f83261b426)

**Comment by fishjar** [comment]
已更新，同步下订阅规则即可。
