### ISSUE TITLE
报告一个不能正常翻译的网站

### ISSUE THREAD

**Issue by pipashu** [fishjar/kiss-translator#64]
https://www.historydefined.net/incredible-photos-with-insane-backstories/
该网站的正文大多无法正常翻译。
![sdfgy](https://github.com/fishjar/kiss-translator/assets/27265628/f87a31f3-161b-477e-9210-a3fb4d333761)

**Comment by fishjar** [comment]
添加个人规则或同步下订阅规则：

```css
.wp-element-caption, :is(li, p, h1, h2, h3, h4, h5, h6, dd, blockquote)
```
