### ISSUE TITLE
[bug] 无法将触摸翻译设置为四指触摸

### ISSUE THREAD

**Issue by 66Leo66** [fishjar/kiss-translator#65]
问题：设置界面“触屏翻译快捷方式”无法选择四指（选择后该设置会自动变成三指）

原因：

https://github.com/fishjar/kiss-translator/blob/535a43b698d3e5c855f9de02d1bcecc767b1aaa4/src/views/Options/Setting.js#L67C2-L67C2

此处代码导致选择四指（value=4）会被错误的limit（0~3）调为三指。

**Comment by fishjar** [comment]
最早只支持到三指，后来加到四指，代码漏改这个地方了。

下个版本修复。
