### ISSUE TITLE
建议一个功能

### ISSUE THREAD

**Issue by pipashu** [fishjar/kiss-translator#66]
隐藏原文，只显示翻译和对照显示，通过快捷键切换。

**Comment by fishjar** [comment]
除非可以接受译文失去部分链接、样式、图片，否则短时间内不会实现此功能，原因和这个issue https://github.com/fishjar/kiss-translator/issues/61 本质上是一样的。

**Comment by C1oudTree** [comment]
可以在规则里添加这个选项吗?把问题丢给规则,只要在规则里测试好了就没问题了

**Comment by fishjar** [comment]
此功能暂时不计划开发，建议使用浏览器自带的全文翻译。
