### ISSUE TITLE
考虑支持 Access Token 实现的 OpenAI 翻译接入？

### ISSUE THREAD

**Issue by gitiy1** [fishjar/kiss-translator#67]
目前 OpenAI API 申请难度对大多数人仍然较大，有项目例如 [chatGPTBox](https://github.com/josStorer/chatGPTBox) 支持基于 Access Token 实现的接入 OpenAI ，这样仅需登录网页账号即可，请问是否可以考虑支持？

Access Token 获取：http://chat.openai.com/api/auth/session
再次感谢开发者的辛勤付出！！！

**Comment by fishjar** [comment]
不错的想法，不过有几个问题需要考虑：
1、不知道chatgpt网页版的对话频率限制如何，能否满足全文对照翻译的需求？
2、是另起项目提供翻译接口，还是集成到插件比较好？
3、如果是独立的项目，也许有人已经实现了。
有时间再研究下。

**Comment by 66Leo66** [comment]
1. 用网页版接口似乎涉及绕过Cloudflare，再加上OpenAI风控严格，我看chatGPTBox的好像需要某个标签页挂着ChatGPT Web，估计就是由于风控啥的。（没试过）
2. 网页版（尤其是非Plus）似乎并发限额（RPM）比较严格，如果一段文字一个请求估计不够，多段合并可能可以。而且比起API回复速度慢不少。
3. 有类似 https://github.com/pandora-next/deploy 这样的项目。好像是不开源，敢不敢用看个人。

**Comment by fishjar** [comment]
这类翻译接口的逆向开发不是本插件核心，交给其他项目比较好，而且本插件已提供了自定义翻译接口的功能。
