### ISSUE TITLE
非常不错的插件，UI搞好点完全就是最好的开源翻译插件了

### ISSUE THREAD

**Issue by Littleweisheit** [fishjar/kiss-translator#68]
我是划词翻译永久版用户，沉浸式翻译也用过（发现是假开源就删除了）。
目前我觉得这个实用性已经很不错了，UI搞好点+OCR，我就能删除划词翻译了
![图片](https://github.com/fishjar/kiss-translator/assets/11383988/e29f49bd-4241-4397-9a9a-0becca11175a)

**Comment by fishjar** [comment]
1、OCR短时间内不会支持。
2、UI有需要提升的地方欢迎指出。

**Comment by Littleweisheit** [comment]
> 1、OCR短时间内不会支持。 2、UI有需要提升的地方欢迎指出。

主要是划词界面吧
![图片](https://github.com/fishjar/kiss-translator/assets/11383988/32fb9535-4283-4dd9-9fbe-cca6b921aad5)
红框里的完全没必要吧，人们不会频繁切换翻译源，划词翻译是直接给多个翻译结果

**Comment by kayanouriko** [comment]
同意, 弹窗 UI 可以参考一下划词翻译的 UI 很整洁, 而且还列举了一系列实用按钮在顶头栏, 但也不喧宾夺主, 就是这个 issue 截图的样子, 大部分的翻译扩展也是这个样子的.
kiss 的 md2 风格在翻译弹窗上确实显得有点奇怪, 翻译内容不突出, 不过鉴于 kiss 整体样式都是 md2 风格的, 所以其实最好是可以提供自定义 css 的功能.
