### ISSUE TITLE
 [Bug report] 迅雷云盘分享页 翻译图标显示异常

### ISSUE THREAD

**Issue by benzBrake** [fishjar/kiss-translator#69]
![xunlei](https://github.com/fishjar/kiss-translator/assets/11323774/a93c75b0-0155-45a8-95ef-ff386b8376f7)

**Comment by fishjar** [comment]
这个页面的问题和百度页面类似，暂无完美的办法解决。

**Comment by benzBrake** [comment]
> 这个页面的问题和百度页面类似，暂无完美的办法解决。

虽然但是，沉浸式的图标是正常的

**Comment by fishjar** [comment]
> > 这个页面的问题和百度页面类似，暂无完美的办法解决。
> 
> 虽然但是，沉浸式的图标是正常的

这本质是 [MUI](https://mui.com/) 继承页面root字体大小引发的问题，但是：
1、真研究了很久都没很好解决，加上出现问题的页面极少就没继续处理了。
2、其实避开问题，把字体图标换成图片也许就解决了，后面会尝试一下。

**Comment by fishjar** [comment]
新版已固定图标文字大小，避免了显示问题。不过如果打开窗口，文字大小还可能有问题，暂不解决。
