### ISSUE TITLE
订阅规则管理页面优化建议

### ISSUE THREAD

**Issue by leic4u** [fishjar/kiss-translator#7]
![image](https://github.com/fishjar/kiss-translator/assets/32786903/29795bdf-bb26-4818-bcf8-f3d5a3a840b2)

使用了下这个功能，有几点建议：

1. 经测试发现，订阅列表不论单选按钮是否选中，订阅中的规则均会生效。
	这里有点歧义，我开始看到单选按钮，还以为是只有单选中的订阅才会生效，原来是单选代表了可以查询和删除当前订阅的意思。
	建议优化一下，不采用单选按钮的形式来管理订阅。目标是让当前生效的是哪些规则更直观。

![image](https://github.com/fishjar/kiss-translator/assets/32786903/144239d2-10be-4799-b041-7f15e9e75d0c)

2. 使用 `ghproxy` 代理的链接，无法订阅成功，建议调整下网址文本的校验规则。

3. 订阅规则支持自动更新，支持 `cron` 表达式就行。

4. 针对订阅中已有的规则的网址页面，如果我想给该网址页面增加页面上某一处的翻译，我必须先去订阅中找到这个地址，把现有的规则复制出来，再在编辑规则中新增一条规则，粘贴上去，再在粘贴的文本之后加上自己的规则。
	否则，如果不去复制粘贴订阅中的规则，只新增自己的，那该页面上就只剩我自己加的那一处翻译了，该页面上其他位置的翻译都没了。
	这个功能目前用起来有点麻烦，希望能支持增量模式，在`编辑规则`中新增了一条规则后，在规则提交的时候把二者做下合并，保存成功后显示为自己新增的+订阅的，类似于 Clash For Windows 的 `mixin` 功能。
	（这个优先级较低）

**Comment by fishjar** [comment]
> 1. 经测试发现，订阅列表不论单选按钮是否选中，订阅中的规则均会生效。

其实`订阅规则`是否生效的按钮在`编辑规则`Tab那里，有个`注入订阅规则`开关控制。

> 2. 使用 `ghproxy` 代理的链接，无法订阅成功，建议调整下网址文本的校验规则。

这个bug我大概知道什么回事了，因为油猴脚本的限制，请求域名必须先在头部定义`@connect`。

有两个解决方案，各有优缺点：

- 将`ghproxy.com`域名加入头部定义。
- 采用网页本直接发出请求，但是需要网址是能跨域访问的。

> 3. 订阅规则支持自动更新，支持 `cron` 表达式就行。

这个还需要仔细考虑下，`cron`是系统级的进程在跑，浏览器不可能一直打开的。

> 4. 针对订阅中已有的规则的网址页面，如果我想给该网址页面增加页面上某一处的翻译，我必须先去订阅中找到这个地址，把现有的规则复制出来，再在编辑规则中新增一条规则，粘贴上去，再在粘贴的文本之后加上自己的规则。
>    否则，如果不去复制粘贴订阅中的规则，只新增自己的，那该页面上就只剩我自己加的那一处翻译了，该页面上其他位置的翻译都没了。
>    这个功能目前用起来有点麻烦，希望能支持增量模式，在`编辑规则`中新增了一条规则后，在规则提交的时候把二者做下合并，保存成功后显示为自己新增的+订阅的，类似于 Clash For Windows 的 `mixin` 功能。
>    （这个优先级较低）

这个逻辑要做的话是能实现的，只是利弊还需再考虑考虑，或者有无其他更优解。

**Comment by leic4u** [comment]
> > 1. 经测试发现，订阅列表不论单选按钮是否选中，订阅中的规则均会生效。
>
> 其实`订阅规则`是否生效的按钮在`编辑规则`Tab那里，有个`注入订阅规则`开关控制。

这个反馈主要是想表达现在的订阅管理方式有点不直观，会导致用户困惑，不好理解。如果可以的话，建议调整为其他布局（类似 ublock origin 那种），或者`订阅规则`也做个列表。

> > 3. 订阅规则支持自动更新，支持 `cron` 表达式就行。
>
> 这个还需要仔细考虑下，`cron`是系统级的进程在跑，浏览器不可能一直打开的。

那就每次打开浏览器的时候自动更新一下？这样好像也可以。

> > 4. 希望能支持增量模式，在`编辑规则`中新增了一条规则后，在规则提交的时候把二者做下合并，保存成功后显示为自己新增的+订阅的，类似于 Clash For Windows 的 `mixin` 功能。
>
> 这个逻辑要做的话是能实现的，只是利弊还需再考虑考虑： 
> * 好处是方便增加需要翻译的地方
> * 但是如果多翻译了一些地方，想要去掉这些翻译，就会做不到了 
> 或者有无其他更优解？

如果想剔除掉`订阅规则`里面的规则的话，暂时没有想到其他方案。我再想想。

**Comment by fishjar** [comment]
> > > 1. 经测试发现，订阅列表不论单选按钮是否选中，订阅中的规则均会生效。
> > 
> > 
> > 其实`订阅规则`是否生效的按钮在`编辑规则`Tab那里，有个`注入订阅规则`开关控制。
> 
> 这个反馈主要是想表达现在的订阅管理方式有点不直观，会导致用户困惑，不好理解。如果可以的话，建议调整为其他布局（类似 ublock origin 那种），或者`订阅规则`也做个列表。
> 

首次使用可能是会有点迷惑，看看有没简单的方案，或许可以增加一些文字说明。

> > > 3. 订阅规则支持自动更新，支持 `cron` 表达式就行。
> > 
> > 
> > 这个还需要仔细考虑下，`cron`是系统级的进程在跑，浏览器不可能一直打开的。
> 
> 那就每次打开浏览器的时候自动更新一下？这样好像也可以。
> 

插件版的比较好解决，油猴脚本的还不知如何实现对浏览器启动的监控。
如果每打开一个页面就更新一下又太频繁了，或许可以记录一个同步时间，打开页面时发现过了多久就更新一次。

> > > 4. 希望能支持增量模式，在`编辑规则`中新增了一条规则后，在规则提交的时候把二者做下合并，保存成功后显示为自己新增的+订阅的，类似于 Clash For Windows 的 `mixin` 功能。
> > 
> > 
> > 这个逻辑要做的话是能实现的，只是利弊还需再考虑考虑：
> > 
> > * 好处是方便增加需要翻译的地方
> > * 但是如果多翻译了一些地方，想要去掉这些翻译，就会做不到了
> >   或者有无其他更优解？
> 
> 如果想剔除掉`订阅规则`里面的规则的话，暂时没有想到其他方案。我再想想。

我想到一个方案，就是在新增规则的时候，自动检索当前域名的匹配规则并给出提示，这样就不需要手工去查找之前填写的，方便很多。

**Comment by leic4u** [comment]
> 我想到一个方案，就是在新增规则的时候，自动检索当前域名的匹配规则并给出提示，这样就不需要手工去查找之前填写的，方便很多。

确实，这种复杂条件下提供足够的信息，让用户自己决定是比较好的方案。
