### ISSUE TITLE
文字消失了~

### ISSUE THREAD

**Issue by kokojacket** [fishjar/kiss-translator#71]
![PixPin_2023-12-26_09-28-08](https://github.com/fishjar/kiss-translator/assets/74887370/4ff9ee9b-1446-4404-ae4d-1bd733c35eeb)

**Comment by fishjar** [comment]
你可能同时使用多个翻译插件引发冲突，正常是这样的：

![Screenshot from 2023-12-26 09-51-34](https://github.com/fishjar/kiss-translator/assets/1157624/ecd9aa93-3a1e-467e-8213-37280d97753d)

**Comment by kokojacket** [comment]
确实是。
