### ISSUE TITLE
请求一个菜单功能

### ISSUE THREAD

**Issue by C1oudTree** [fishjar/kiss-translator#73]
可以在这个菜单加一个编辑匹配网址的功能吗
![image](https://github.com/fishjar/kiss-translator/assets/90253489/5d49555a-8bf4-4f0e-9c67-514ef3a2e131)

基本上所有点击"保存规则"的操作都需要再进入设置页面编辑规则

比如:

在这个网页保存规则时https://github.com/fishjar/kiss-translator/issues/new

我需要再进入设置页面修改为github.com

**Comment by fishjar** [comment]
当时考虑过在保存规则时：
1、是保存完整的地址：`https://github.com/fishjar/kiss-translator/issues/new`
2、还是提取域名保存：`github.com`
3、还是在这里显示一个域名编辑框

最终选择保存完整地址，因为：
1、这是一个低频功能，占用一个位置会显得多余
2、到设置页面删除网址的一部分比补充网址简单

现在考虑要不要在点击`保存规则`后，立即跳转到设置页面，因为保存后，很可能需要进一步修改网址和选择器等。

**Comment by fishjar** [comment]
之前的保存按钮是保存当前页面，新版已改为保存当前域名的规则。
