### ISSUE TITLE
[咨询]能否添加"显示翻译框/选中翻译框文字"快捷键到catsxp://extensions/shortcuts

### ISSUE THREAD

**Issue by lakevilladom** [fishjar/kiss-translator#75]
![image](https://github.com/fishjar/kiss-translator/assets/22128667/9a44b629-ec62-483e-a9a3-20fcbea0add7)

如上图，可以设置快捷键为全局，更加方便地随时调出翻译框。

**Comment by fishjar** [comment]
可以考虑，好像刚好还有一个快捷键位置

**Comment by fishjar** [comment]
新版已实现
