### ISSUE TITLE
[Feature Request] 添加lingva translate支持

### ISSUE THREAD

**Issue by showgood163** [fishjar/kiss-translator#76]
[lingva translate](https://github.com/thedaviddelta/lingva-translate)是google translate的另一种前端，可以为用户提供更好的隐私保护。

上述页面中包含对公共API的的描述，使用GET方法而不是POST方法，因此无法用本插件中提供的custom接口实现。

**Comment by fishjar** [comment]
看了下，说实话不大明白这个项目是如何实现隐私保护的。
这比在代理的情况下调用谷歌接口有更好的隐私保护？

**Comment by showgood163** [comment]
> 看了下，说实话不大明白这个项目是如何实现隐私保护的。 这比在代理的情况下调用谷歌接口有更好的隐私保护？

这个项目和[NewPipe](https://github.com/TeamNewPipe/NewPipe), [Nitter](https://github.com/zedeus/nitter), [Invidious](https://github.com/iv-org/invidious) or [Bibliogram](https://git.sr.ht/~cadence/bibliogram)类似，都是建立镜像站来中转请求。

隐私保护方面，这项目做的和cloudflare类似，避免用户ip直接暴露给google/facebook/twitter等大公司服务器。同时，不同用户的请求都是通过同一个服务器发出的，服务器很难反向追踪。

**Comment by fishjar** [comment]
实际上我提供的这个代理也实现了类似的隐私保护功能 https://github.com/fishjar/kiss-proxy

理论上谷歌只能追踪到cloudflare的CDN服务器

**Comment by showgood163** [comment]
> 实际上我提供的这个代理也实现了类似的隐私保护功能 https://github.com/fishjar/kiss-proxy
> 
> 理论上谷歌只能追踪到cloudflare的CDN服务器

我直连在cloudflare worker搭建的v2ray代理，访问不少新闻网站时都会因为我所在的地理位置被屏蔽，即使我连接的cdn节点所在位置和我所在国家不同。

这让我怀疑，如果不去显式在配置文件中修改源ip，cf workers上的服务就会暴露源ip。

我简单看了一下kiss-proxy的源码，没看到ip处理的部分，这可能是个问题。当然我是不太懂这块，说的有问题就请多指教。

**Comment by showgood163** [comment]
另外我最开始遇到的问题是 https://github.com/fishjar/kiss-rules/issues/22 。
我想着为每个有登录账号的网站都去做适配，工作量会很离谱，于是有了这个问题。

**Comment by fishjar** [comment]
> > 实际上我提供的这个代理也实现了类似的隐私保护功能 https://github.com/fishjar/kiss-proxy
> > 理论上谷歌只能追踪到cloudflare的CDN服务器
> 
> 我直连在cloudflare worker搭建的v2ray代理（比如 https://github.com/3Kmfi6HP/EDtunnel ），访问不少新闻网站时都会因为我所在的地理位置被屏蔽，即使我连接的cdn节点所在位置和我所在国家不同。
> 
> 这让我怀疑，如果不去显式在配置文件中修改源ip，cf workers上的服务就会暴露源ip。
> 
> 我简单看了一下kiss-proxy的源码，没看到ip处理的部分，这可能是个问题。当然我是不太懂这块，说的有问题就请多指教。

你这么一说我也不是很肯定 kiss-proxy 的写法是否会暴露客户端源IP了，我没有做过相关测试。
