### ISSUE TITLE
input 元素中的快捷键在 macOS 的 Firefox 中不起作用

### ISSUE THREAD

**Issue by laipz8200** [fishjar/kiss-translator#77]
## 问题

默认的输入框翻译快捷键 Alt+I 在 macOS 平台的 Firefox 浏览器上无法稳定触发。实际上任何 Alt + 字母均无法触发。

## 详情

macOS 系统的默认行为是 option（alt） + 字母用于输入特殊符号。

Firefox 中，在 input 上使用该组合键会导致输入一个特殊符号而不是触发翻译。但同样是 macOS 下的 Chrome 浏览器则没有这个问题。

### 系统和软件

```
macOS 14.2.1
Firefox 121.0
Chrome 120.0.6099.199
```

### 场景

[ChatGPT](https://chat.openai.com/)

**Comment by fishjar** [comment]
换其他的`触发快捷键`试试
