### ISSUE TITLE
火狐扩展小窗快捷键显示问题

### ISSUE THREAD

**Issue by kidzgy** [fishjar/kiss-translator#78]
![微信截图_20240110094311](https://github.com/fishjar/kiss-translator/assets/6967810/98797cf7-d1a2-4cd5-bbe4-8dffb8f94af3)
火狐扩展的快捷键是可以独立设置的，在附加组件管理页。无论我将扩展的快捷键设置成什么，扩展小窗显示的快捷键，固定是 “翻译（ALT+Q）”以及“设置（ALT+O）”， 不知可否将 显示的快捷键（ALT+Q、ALT+O）跟随火狐实际设置的快捷键呢？

**Comment by fishjar** [comment]
我这里测试没发现你说的问题，
1、是不是快捷键冲突了
2、升级到最新版或删掉重装试试

**Comment by kidzgy** [comment]
![微信截图_20240110164231](https://github.com/fishjar/kiss-translator/assets/6967810/a0d4c06f-8f13-49e5-89d2-d2ecf9e15967)
![微信截图_20240110164219](https://github.com/fishjar/kiss-translator/assets/6967810/278adb16-ce32-4f72-bba2-5a0ffee376df)

我的意思是，在火狐附件组件设置快捷键为其他，比如ALT+S的时候，弹出的小窗上显示的快捷键依旧为ALT+Q。
刚刚已经重装过扩展了

**Comment by fishjar** [comment]
明白了，我以为设置的快捷键无效。。这个文字显示可以忽略，写死的，只是一个提示作用。
如要动态改变，也许有点麻烦，还有右键菜单也有。

**Comment by fishjar** [comment]
新版已修改
