### ISSUE TITLE
建议增加的功能

### ISSUE THREAD

**Issue by Sirius2016** [fishjar/kiss-translator#79]
1、建议增加标题翻译
2、打开网页时增加从文章顶部，翻译到底部。

**Comment by fishjar** [comment]
1、标题翻译是指浏览器顶部显示的标题？
2、一次性全部翻译完的使用场景是怎样的？

**Comment by Sirius2016** [comment]
是的，标题翻译是指浏览器顶部显示的标题。
一次性全部翻译完的使用场景是：看到好的英文站点内容，把页面全部翻译之后，离线存储到本地，方便以后查看。

**Comment by fishjar** [comment]
> 是的，标题翻译是指浏览器顶部显示的标题。
增加这个功能应该问题不大

> 一次性全部翻译完的使用场景是：看到好的英文站点内容，把页面全部翻译之后，离线存储到本地，方便以后查看。
之前没有考虑过这个需求，有时间研究下好不好实现

**Comment by fishjar** [comment]
新版已实现
