### ISSUE TITLE
[feature request]订阅规则支持多选，同时注入多个订阅的规则

### ISSUE THREAD

**Issue by leic4u** [fishjar/kiss-translator#8]
把订阅规则展示到个人规则中之后，才发现这个问题，原来单选按钮的作用是**控制启用状态**，现在应该是只支持启用一个订阅的，期望可以支持同时启用多个订阅。

**Comment by leic4u** [comment]
> 多选会复杂一些，涉及到一个顺序问题。

订阅规则反正是不能改的，这个能否不考虑顺序，取并集？

> 刷新页面会检查订阅规则的缓存，没有的话会从远程拉取，如果选择多项，可能会影响加载速度。

这个是不是只有在第一次会拉取，本地有缓存之后，应该只是做定时更新了吧？

> 而且目前需求订阅的人估计不多，能分享订阅链接的人更少，等有足够多的反馈再改进这块功能或许会更好。

这里有个死循环，就是如果订阅规则做得不是很易用，那可能愿意分享的人也会变少。分享变少，使用订阅的人也会变少。这样就一直发展不起来。
如果能把一些订阅分享的痛点问题解决掉，其实是非常有利于社区性地传播的。

比如我，我是想在官方规则之外分享一些小众网站的规则。
但是目前阻挠我提供订阅的原因就是，如果我启用小众网站规则，那官方规则就无法使用了。
如果我想同时使用官方规则和小众网站规则，目前唯一的办法就是，先把官方规则 copy 过来，再在官方规则上增加小众网站规则。
但这样如果官方规则发生变更，一是可能我不知道（这样就产生了分叉），二是如果我知道了我需要手动去 copy 官方规则更新到我的订阅里面。订阅的维护成本有点高。

不过现在插件刚起步不久，用户量不多，订阅规则也是前几天才上线，订阅分享者也几乎没有。这个优先级确实可以靠后，但建议订阅多选这个功能，可以慢慢做着走。（因为可能不知道哪天本插件就突然爆火了😋）

**Comment by fishjar** [comment]
无其他用户响应，暂时关闭，有需要再打开。
