### ISSUE TITLE
是否有术语功能？

### ISSUE THREAD

**Issue by kiwiflydream** [fishjar/kiss-translator#80]
有些词有很多意思，比如 "String" ，在技术文章中都是"字符串"的意思，但是经常被翻译成"绳索"。有些词是公司名或者特定名词，但会被直译。能否添加一个自定义术语的功能，手动指定哪些词翻译成什么

**Comment by fishjar** [comment]
可以增加这个功能，唯一问题是，这个术语列表在规则中设置，还是全局设置

**Comment by fishjar** [comment]
感觉还是在规则中更好一些，比如`crate`在rust相关页面不需要翻译，但在其他页面不翻译就不通顺了。
使用上的复杂性可以通过`*`全局规则设置兜底。
开发上的复杂性没得避免。

**Comment by kiwiflydream** [comment]
是的😂

**Comment by fishjar** [comment]
新版已实现

**Comment by kiwiflydream** [comment]
> 新版已实现

感谢更新，不过，似乎有些场景会有问题。比如我设置 "port,端口" 。会把 "export" 导出翻译成，"ex端口" 或者 "前端口"。看了一下请求，似乎是把 "export" 转化为 "ex[0]" 去请求。这的确是一个巧妙的办法，应该满足大部分场景了。但是当术语是某个单词的一部分就会出现问题。

我尝试如下配置" port 端口; port,端口;port ,端口" 想让插件识别 port 为一个独立单词才替换，但是没有成功，可能设置的规则会被 trim 一下。不过即使没有 trim，这仍然不是一个完美的方式，因为除非 port 左右都有空格时才会完美匹配，其它情况还是有问题。况且还不只空格这一种情况，比如下划线、中划线、@等等。

最重要的是，即使能穷举出可能的符号，但是这也只适用于英文这种拼写的语言。像中文、日语之类的，词语与词语之间是没有空格分隔的。如果要实现，可能还得使用分词技术，成本太高。

我想了一个方式，就是先把术语先按目标语言翻译，然后用把术语的翻译结果到完整句子的翻译结果中匹配。找到后，替换成术语。但是，翻译结果不一定是稳定的，同一个单词在不同的语境可能结果也不一样。也解决不了问题。

所以，可能术语这个功能没有比较完美的解决办法。🤣

**Comment by fishjar** [comment]
是的，我在实现这个功能的过程中就发现了许多的问题。好在这只是一个可选功能，不填术语的话几乎没有影响。

1、拆分单词的问题，或许可以针对英文再稍微优化一下，同时匹配前后不是英文字符的情况才替换。
2、术语用占位符替换后，对某些句子割裂严重，会影响翻译结果的正确性。

总而言之，慎用。

![Screenshot from 2024-01-30 20-10-53](https://github.com/fishjar/kiss-translator/assets/1157624/5e826e38-15ba-4cd3-b30e-4a537d948daf)

**Comment by kiwiflydream** [comment]
> 是的，我在实现这个功能的过程中就发现了许多的问题。好在这只是一个可选功能，不填术语的话几乎没有影响。
> 
> 1、拆分单词的问题，或许可以针对英文再稍微优化一下，同时匹配前后不是英文字符的情况才替换。 2、术语用占位符替换后，对某些句子割裂严重，会影响翻译结果的正确性。
> 
> 总而言之，慎用。
> 
> ![Screenshot from 2024-01-30 20-10-53](https://private-user-images.githubusercontent.com/1157624/300800550-5e826e38-15ba-4cd3-b30e-4a537d948daf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MTc1OTcsIm5iZiI6MTcwNjYxNzI5NywicGF0aCI6Ii8xMTU3NjI0LzMwMDgwMDU1MC01ZTgyNmUzOC0xNWJhLTRjZDMtYjMwZS00YTUzN2Q5NDhkYWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMzBUMTIyMTM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTRjNzc3YTUzOWI0MjNmMjRhZDllYjM5MWJlZGNhMTIwZDg1MWJhNTVkNWEzYmZmOGEzYjM1ODY5MzdlMzAxMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7l2_uYYcOJERoRDMA6QYrwZMa0bUBRkwTP4P6VTgnYU)

明白了，感谢 🙏

**Comment by fishjar** [comment]
[v1.8.1](https://github.com/fishjar/kiss-translator/releases/tag/v1.8.1) 已优化：

  - 通过正则匹配，可避免英文单词拆分替换。
  - 比如`React`单词
    - 如果设置术语 `act, 表演`，会导致拆分翻译成 `回复表演`
    - 如果设置术语 `\bact\b, 表演`，则不会拆分单词
