### ISSUE TITLE
[Feature Request] 鼠标悬停翻译功能不依赖翻译开关，并且可以绕过规则选择器

### ISSUE THREAD

**Issue by GoodbyeNJN** [fishjar/kiss-translator#82]
复现步骤：
1. 全局规则默认关闭翻译，订阅规则使用 `kiss-rules-off.json`
2. 打开 [Stack Exchange](https://stackexchange.com)，按下 `Alt+Q`

现象：
1. 使用脚本版时，似乎命中了全局规则，开始自动翻译网页全文
2. 使用扩展版时，应同样自动翻译全文，实际是未开始翻译

环境：
1. Chrome 120.0.6099.217
2. Tampermonkey Beta 5.0.6192
3. KISS Translator 1.7.16

**Comment by fishjar** [comment]
没有复现问题，重新设置快捷键或重安装试试。

**Comment by GoodbyeNJN** [comment]
进一步测试发现，鼠标悬停翻译功能不仅受 `Alt+Q` 开关控制，也受规则中的选择器影响。

例如，在默认的全局规则下，针对某个 [Stack Exchange 问题详情页](https://travel.stackexchange.com/questions/185782/why-do-schengen-consulates-care-about-visa-shopping)，comments 部分在全文翻译/鼠标悬停翻译时都会被忽略。

而在某些场景下，可能会出现这两种需求：
1. 未开启 `Alt+Q` 开关，阅读原文时需要临时翻译某个段落
2. 已开启 `Alt+Q` 开关，但某个段落未被翻译，此时想临时补充翻译这个段落

虽然能通过划词翻译实现，但相对来说鼠标悬停翻译更加方便。所以我想能不能让鼠标悬停翻译功能不依赖 `Alt+Q` 开关，并且(可选地)可以绕过规则选择器。

**Comment by fishjar** [comment]
> 进一步测试发现，鼠标悬停翻译功能不仅受翻译开关控制，也受规则中的选择器影响。
> 
> 例如，在默认的全局规则下，针对某个 [Stack Exchange 问题详情页](https://travel.stackexchange.com/questions/185782/why-do-schengen-consulates-care-about-visa-shopping)，comments 部分在全文翻译/鼠标悬停翻译时都会被忽略。
> 
> 而在某些场景下，可能会出现这两种需求：
> 
> 1. 未开启翻译开关，阅读原文时需要临时翻译某个段落
> 2. 已开启翻译开关，但某个段落未被翻译，此时想临时补充翻译这个段落
> 
> 虽然能通过划词翻译实现，但相对来说鼠标悬停翻译更加方便。所以我想能不能让鼠标悬停翻译功能不依赖翻译开关，并且(可选地)可以绕过规则选择器。

本来设计就是如此的，鼠标悬停只是翻译的时机，最终受翻译开关和翻译规则限制。

你说的这个随意翻译鼠标所指内容，不是一个常用功能，对代码改动和性能影响较大，收益太低，所以暂时不会改变目前的逻辑。
