### ISSUE TITLE
[咨询]为什么弹窗翻译的"原文"输入框灰色的需要点好几次才能点亮输入

### ISSUE THREAD

**Issue by lakevilladom** [fishjar/kiss-translator#84]
![image](https://github.com/fishjar/kiss-translator/assets/22128667/f651f1ab-db8c-41a9-91c1-f552f158b8c4)

我一般在VS Code看到一段英文，就会拷贝到弹窗翻译来翻译，但是"原文"输入框灰色，需要上面随机乱点好几次，才会突然变得可输入，这个是我操作问题吗，

另外提如下建议：
这个翻译弹窗在浏览器失去焦点的情况下也能弹出到屏幕最顶部，比如我在用VS Code编辑的时候发现需要翻译的内容，直接按快捷键直接能调出这个弹窗到屏幕最顶端，直接翻译。(我明白这个扩展是安装在浏览器上的，不是在操作系统上的，这个建议只是我天马行空的想法，也许压根就不可行)

**Comment by fishjar** [comment]
1、不知道你用的什么浏览器，一般是点一下灰色`原文`框就能输入了。
2、你这个天马行空的想法其实已经实现了一半，简单设置即可，如下图（注意右下角那个Global）。

![Screenshot from 2024-01-24 18-01-30](https://github.com/fishjar/kiss-translator/assets/1157624/9a87236f-f216-4650-bcc3-5c308d667ed1)

**Comment by lakevilladom** [comment]
1、我主力用猫眼浏览器，我刚用谷歌浏览器测试也是不灵，有时候点一下就就OK,有时候点半天
[toolwa 录制 -2024024-4a09ofngwi3.webm](https://github.com/fishjar/kiss-translator/assets/22128667/b4455de5-5c1e-4004-babe-32d445893458)
2、这个Global我是配置了的，这个我的意思其实浏览器在最小化或者失去焦点的时候，按Alt+S也能置顶弹出这个翻译框，但是这个想法我测试发现不现实，如果其他软件获得焦点的时候，这个快捷键就会在这个软件上生效，这个建议忽略吧

**Comment by fishjar** [comment]
> 1、我主力用猫眼浏览器，我刚用谷歌浏览器测试也是不灵，有时候点一下就就OK,有时候点半天

那就有点奇怪了，我这里没发现不灵的情况。不知是不是你有其他插件影响到了。可以隐身模式测试一下。或者不要在baidu页面，换个网页唤起试试。

> 2、这个Global我是配置了的，这个我的意思其实浏览器在最小化或者失去焦点的时候，按Alt+S也能置顶弹出这个翻译框，但是这个想法我测试发现不现实，如果其他软件获得焦点的时候，这个快捷键就会在这个软件上生效，这个建议忽略吧

这个Global就是浏览器在最小化或失去焦点时也可以弹出翻译框，只是不能最小化时唤起浏览器。如果其他软件焦点时不能弹出翻译框，可能是快捷键冲突，可以换一个快捷键试试。

注意，不要完全按照我上面的图，你要在 `Translate Popup/Slected` 那一栏设置 Global。
