### ISSUE TITLE
怎么设置不翻译网页标题？

### ISSUE THREAD

**Issue by u3u** [fishjar/kiss-translator#85]
我记得之前是没有的，现在这样过度翻译有点傻。。
<img width="513" alt="image" src="https://github.com/fishjar/kiss-translator/assets/20062482/4376e15d-24a9-426c-b8f7-8c63a97b66dd">

**Comment by fishjar** [comment]
暂时没法设置，下个版本加个开关吧。

**Comment by fishjar** [comment]
新版已增加设置开关

**Comment by u3u** [comment]
谢谢！
