### ISSUE TITLE
网站 forum.mozilla-russia.org 翻译细节问题求助

### ISSUE THREAD

**Issue by benzBrake** [fishjar/kiss-translator#86]
浏览器是 Firefox 122
已经尝试过更新简约翻译到最新版了

示例URL：https://forum.mozilla-russia.org/viewtopic.php?id=76642

这是简约翻译的效果
![简约](https://github.com/fishjar/kiss-translator/assets/11323774/f9569356-0cc5-4b51-997b-5e5d8be6c15a)
这是沉浸式的效果
![沉浸式](https://github.com/fishjar/kiss-translator/assets/11323774/25ad10b2-21d2-4451-909c-46c620081f20)

**Comment by fishjar** [comment]
依照下图，设置一下即可：

![Screenshot from 2024-01-31 23-30-37](https://github.com/fishjar/kiss-translator/assets/1157624/cb8e4bc7-8e73-456f-841e-eef5e88a6640)

效果：

![Screenshot from 2024-01-31 23-30-58](https://github.com/fishjar/kiss-translator/assets/1157624/7ef0db86-e047-4125-a827-6bcd209dd31b)
