### ISSUE TITLE
火狐扩展，右键菜单明明已启用，重启后却丢失菜单

### ISSUE THREAD

**Issue by kidzgy** [fishjar/kiss-translator#87]
FF121，扩展1.8.0。

扩展设置，右键菜单为启用状态，重启浏览器后，右键菜单消失。

并且再反馈个问题，明明已启用翻译，右键菜单的文本仍旧【开启翻译】，并且希望右键菜单的几个菜单，可以调整次序和设置是否显示。
![2024-02-01_193018](https://github.com/fishjar/kiss-translator/assets/6967810/1b616249-5c24-4fa4-aa77-59d639da50c8)

**Comment by fishjar** [comment]
1、确实，firefox重启后右键菜单没了，下个版本尝试修复一下。
2、右键菜单的`开启翻译`是一个固定的文本，不会根据当前状态改变，或许改成`切换翻译`更合适。
3、自由调整右键菜单的功能可以做到，但会大大增加操作复杂性，而右键菜单很少人使用，所以暂时不会增加这个功能。

**Comment by kidzgy** [comment]
更新到1.8.1，菜单问题修复了，另外想提个建议，就是右键菜单启用可否分两种菜单，一种是默认的折叠菜单，另外一种是去除折叠菜单，右键弹出的一级菜单即是翻译开关，去掉切换样式以及打开设置等。 因为切换样式和打开设置等菜单是低频操作，这个可以直接从扩展图标上进入，而翻译就不一样了，有时候临时需要开启翻译，直接右键就方便很多。

**Comment by fishjar** [comment]
没问题，下个版本优化下，多一种选择。

**Comment by kidzgy** [comment]
当一级菜单即是翻译开关时，名称可不可以改为【简约翻译】，因为菜单名称本身不会对开启或关闭状态作出识别，所以“启停”二字本身无太大意义，直接用“简约翻译”更为恰当。

**Comment by fishjar** [comment]
没问题

**Comment by charley008** [comment]
目前网页右键菜单始终显示「开启翻译」。

例如：

1. 打开一个英文网页；
2. 右键选择「开启翻译」；
3. 网页已经进入翻译状态；
4. 再次右键，菜单仍然显示「开启翻译」。

这样会比较容易产生困惑。

希望右键菜单可以根据当前网页的翻译状态动态变化，例如：

- 未开启翻译时：显示「开启翻译」
- 已开启翻译时：显示「关闭翻译」或「恢复原文」

这样同一个右键菜单项就可以直接作为翻译状态的开关，而不用打开扩展面板再关闭翻译。

我个人觉得相比固定显示「开启翻译」或者「切换翻译」，动态显示「开启翻译 / 恢复原文」会更加直观。

**Comment by kidzgy** [comment]
> 目前网页右键菜单始终显示「开启翻译」。
> 
> 例如：
> 
>     1. 打开一个英文网页；
> 
>     2. 右键选择「开启翻译」；
> 
>     3. 网页已经进入翻译状态；
> 
>     4. 再次右键，菜单仍然显示「开启翻译」。
> 
> 
> 这样会比较容易产生困惑。
> 
> 希望右键菜单可以根据当前网页的翻译状态动态变化，例如：
> 
>     * 未开启翻译时：显示「开启翻译」
> 
>     * 已开启翻译时：显示「关闭翻译」或「恢复原文」
> 
> 
> 这样同一个右键菜单项就可以直接作为翻译状态的开关，而不用打开扩展面板再关闭翻译。
> 
> 我个人觉得相比固定显示「开启翻译」或者「切换翻译」，动态显示「开启翻译 / 恢复原文」会更加直观。

正这是我想要的效果，而且只需要一级菜单就行了，二级菜单完全没有必要。

**Comment by charley008** [comment]
另外感觉这个图标不是很优美

<img width="134" height="116" alt="Image" src="https://github.com/user-attachments/assets/180d8ac1-583a-4bb9-a949-b7e29979b95e" />

**Comment by fishjar** [comment]
1、文本已有PR修改：https://github.com/fishjar/kiss-translator/pull/1071

2、显示一级菜单还是二级菜单可以设置的，自由选择。

3、这个图标在最新UI中有改变，虽然也不是很优美，后面再考虑下

<img width="295" height="194" alt="Image" src="https://github.com/user-attachments/assets/fdc7fd1e-edf7-4811-adbc-f6f1486a43da" />
