### ISSUE TITLE
在xda论坛上不能正确翻译

### ISSUE THREAD

**Issue by yhx0022** [fishjar/kiss-translator#88]
我用的是火狐浏览器，脚本管理插件是暴力猴。
安装了kiss翻译脚本后，在xda论坛上不能正确翻译评论。

**Comment by fishjar** [comment]
发个链接

**Comment by yhx0022** [comment]
> 发个链接

https://xdaforums.com/t/rom-14-0_r20-marble-official-evolution-x-01-30-24.4640655/page-2

xda论坛是国外一个专门讨论手机的地方。
目前就是翻译不了别人发表的评论，但偏偏能翻译到“被引用的评论”。

**Comment by fishjar** [comment]
参考下图规则，不过还有点小问题，引用后面第一句不会翻译，因为代码漏了一个`BLOCKQUOTE`，下个版本修复。

![Screenshot from 2024-02-05 10-53-35](https://github.com/fishjar/kiss-translator/assets/1157624/81debdb3-d067-4b77-9e01-fe664506f82f)

![Screenshot from 2024-02-05 10-53-02](https://github.com/fishjar/kiss-translator/assets/1157624/8fb09b70-1ca8-46b0-a77a-3a85f1ed4f25)

**Comment by yhx0022** [comment]
> 参考下图规则，不过还有点小问题，引用后面第一句不会翻译，因为代码漏了一个`BLOCKQUOTE`，下个版本修复。
> 
> ![Screenshot from 2024-02-05 10-53-35](https://private-user-images.githubusercontent.com/1157624/302163422-81debdb3-d067-4b77-9e01-fe664506f82f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMTI0NjcsIm5iZiI6MTcwNzIxMjE2NywicGF0aCI6Ii8xMTU3NjI0LzMwMjE2MzQyMi04MWRlYmRiMy1kMDY3LTRiNzctOWUwMS1mZTY2NDUwNmY4MmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDZUMDkzNjA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGNjZjBjMDQ1OGQwNDZhZTA3YzBiNmRhOTZiNTk5Y2NjYmUwZTZmMjJmMDM1MTk0NjdjZWMzMjcyNGMwYWQxNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.24g7t4Ul86_jPwZ-P0eUxNV0qbKrIoPpy2x4ywASRPQ)
> 
> ![Screenshot from 2024-02-05 10-53-02](https://private-user-images.githubusercontent.com/1157624/302163429-8fb09b70-1ca8-46b0-a77a-3a85f1ed4f25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMTI0NjcsIm5iZiI6MTcwNzIxMjE2NywicGF0aCI6Ii8xMTU3NjI0LzMwMjE2MzQyOS04ZmIwOWI3MC0xY2E4LTQ2YjAtYTc3YS0zYTg1ZjFlZDRmMjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDZUMDkzNjA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZThkZDQ1YmM1YWNkM2E3ODY3NWI0ZDkxMmZkN2NmNDk4YjcxMmUxMTRmYzUzNDAzN2QzZmIwZjAwNWIzMGI4ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dK7zXHRA9K6mTfLxbh3txpaHiT_b_aU53p5ZTu-LgSc)

今天更新了kiss翻译脚本。
但在xda论坛上还是老毛病

**Comment by SkywalkerJi** [comment]
> 1、看不到你发的图 2、更新了插件，规则和补丁，也要按我上面的配置，因为我没有更新规则

现在的版本似乎没有补丁设置，要如何设置翻译xda？

**Comment by fishjar** [comment]
> > 1、看不到你发的图 2、更新了插件，规则和补丁，也要按我上面的配置，因为我没有更新规则
> 
> 现在的版本似乎没有补丁设置，要如何设置翻译xda？

规则设置，点击更多，才能看到补丁设置
