### ISSUE TITLE
支持快捷手势

### ISSUE THREAD

**Issue by Typhonling** [fishjar/kiss-translator#9]
看到新版本增加了快捷键。未来有没有支持快捷手势的打算？触屏上使用。

**Comment by fishjar** [comment]
需要研究下再看看，尚不清楚快捷手势在不同客户端的支持情况如何，不知好不好适配。

**Comment by shangrenxi** [comment]
1. mac上使用Violentmonkey管理脚本，快捷键alt+q无效；
2. 希望增加快捷键+鼠标指针指示翻译该段落的功能

**Comment by fishjar** [comment]
> 1. mac上使用Violentmonkey管理脚本，快捷键alt+q无效；

在mac上用的什么浏览器呢？


> 2. 希望增加快捷键+鼠标指针指示翻译该段落的功能

这个功能还在考虑要不要实现。

其实现在有变通的方式，选模糊效果，鼠标移上去显示清晰。

**Comment by fishjar** [comment]
> 1. mac上使用Violentmonkey管理脚本，快捷键alt+q无效；

新版支持自定义快捷键，可以试试

> 2. 希望增加快捷键+鼠标指针指示翻译该段落的功能

新版已支持鼠标悬停翻译

**Comment by fishjar** [comment]
快捷手势涉及众多平台及众多客户端，有心无力。。

**Comment by fishjar** [comment]
新版已支持双指/三指触摸翻译

https://github.com/fishjar/kiss-translator/releases/tag/v1.7.12
