### ISSUE TITLE
在https://ytscribe.com/v/oIur9NATg-I不工作

### ISSUE THREAD

**Issue by saccohuo** [fishjar/kiss-translator#90]
加了补丁，但是还是没翻译
![image](https://github.com/fishjar/kiss-translator/assets/13887263/b9146c57-68d6-4b05-aa01-ee91f5c50ff5)

**Comment by fishjar** [comment]
参考：

![Screenshot from 2024-02-18 10-22-29](https://github.com/fishjar/kiss-translator/assets/1157624/c9b432a3-02e8-4df0-a433-2a46f0834ad6)
