### ISSUE TITLE
[feature request]Youtube自动生成字幕翻译跟不上

### ISSUE THREAD

**Issue by pullopen** [fishjar/kiss-translator#92]
希望能增加Youtube双语字幕功能。目前翻译速度跟不上语速，而且如果是自动生成的字幕会一个一个词翻，无法连成句子。

**Comment by fishjar** [comment]
本插件字幕翻译确实有些鸡肋，目前最好的方案是，禁用本插件的字幕翻译（参考： https://github.com/fishjar/kiss-translator/issues/62#issuecomment-1844199274 ），选择其他的字幕翻译外挂插件。： https://github.com/fishjar/kiss-translator/issues/74
