### ISSUE TITLE
Firefox重啟後這個extension會不見

### ISSUE THREAD

**Issue by sean-yang** [fishjar/kiss-translator#93]
剛裝完可以用，但重啟後這個extension連在右上角的extension list都不在了，但在add-on manager裡面還在且turn-on，算bug吧，請查看一下！

**Comment by fishjar** [comment]
是什么版本的firefox？

**Comment by sean-yang** [comment]
現在是122.0.1（最新版），之前的版本也有問題！

**Comment by fishjar** [comment]
我用119.0.1版本没发现你说的问题，是否安装了其他插件引起的？或者重新安装插件试试。

**Comment by sean-yang** [comment]
是的，我裝了不少插件！我來試試disable幾個試試！

**Comment by sean-yang** [comment]
我把所有插件都disabled，只留下Kiss Translator，但發現這些應該被disabled的插件雖然在extension manager裡已被標示成disabled，但事實上它們並沒有被disabled，這個問題更大，我可能得重裝firefox了！我想可以先把這個issue close掉，等我重裝firefox試了若還有問題再說，謝謝！
