### ISSUE TITLE
翻译noop时弹窗闪退

### ISSUE THREAD

**Issue by WindWilliam** [fishjar/kiss-translator#94]
Edge浏览器，选词翻译的时候，单纯选中 **noop**  的时候，界面会闪退，但是带有noop的语句，比如 **noop test** 不会。

**Comment by fishjar** [comment]
当某个单词没有发音的时候，会出现，下个版本修复。

**Comment by WindWilliam** [comment]
> 当某个单词没有发音的时候，会出现，下个版本修复。

🆗，辛苦大佬~~

**Comment by fishjar** [comment]
新版已修复
