### ISSUE TITLE
github ipynb无法加载

### ISSUE THREAD

**Issue by Long0x0** [fishjar/kiss-translator#95]
扩展和页面的通信，影响了页面和iframe的通信。很多翻译扩展都会有这个问题。
https://github.com/crimx/ext-saladict/issues/2093
https://github.com/orgs/community/discussions/64876

[测试页面](https://github.com/Layout-Parser/layout-parser/blob/main/examples/OCR%20Tables%20and%20Parse%20the%20Output.ipynb)

或许可以用`runtime.connect`替换`sendMessage`。

**Comment by fishjar** [comment]
具体原因不清楚，把iframe页面加入`禁用翻译黑名单`即可简单解决：

```sh
https://notebooks.githubusercontent.com/view/ipynb*
```

![Screenshot from 2024-02-22 11-42-01](https://github.com/fishjar/kiss-translator/assets/1157624/65d6a487-2ea9-4cf5-89a8-093c8a00d375)

**Comment by Long0x0** [comment]
加入禁用确实正常了，但是就不能翻译了。
immersive translate没有这个问题，不过也不开源，不知道是怎么实现的。
目前写了一个油猴脚本强行patch：
```js
// ==UserScript==
// @name         github .ipynb preview patch
// @version      0.0.1
// @description  fix github .ipynb preview bug
// @license      MIT
// @match        https://github.com/*.ipynb
// @run-at       document-start
// @grant        none
// ==/UserScript==

const __addEventListener = window.addEventListener;
window.addEventListener = function(type, listener, options) {
    if(type === "message" && listener.toString().includes(`("ERROR")`)) {
        const __listener = listener;
        listener = function(event) {
            if(event.data?.action === "trans_getrule") {
                console.log('ignore', event.data);
            } else {
                __listener(event);
            }
        }
    }
    __addEventListener(type, listener, options);
}
```

**Comment by fishjar** [comment]
1、这个很可能是github代码的问题，类似这个 issue： https://github.com/fishjar/kiss-translator/issues/50#issuecomment-1825126129

2、在iframe中发送消息给parent会触发问题，接受消息则没有问题，所以应该可以修复一下，ifame中只单向接受消息即可。

3、关于iframe页面，其实之前就有个纠结的问题，即iframe中的规则要不要和parent的规则共用。

- 如果规则不共用，但快捷键等操作肯定要共用，则可能会造成`是否翻译`的状态混乱。
- 如果共用的话也不太合理，ifame和parent页面元素结构完全不同，规则大相径庭。

之前的做法是选择共用，所以iframe需要从parent获取规则信息。通过修复这个bug，顺便改变一下这个规则，即iframe和parent规则分开定义，状态混淆的问题可以设置一致的规则状态即可避免。

**Comment by fishjar** [comment]
下个版本将修复，需要添加iframe页面的规则：

![Screenshot from 2024-02-22 17-29-07](https://github.com/fishjar/kiss-translator/assets/1157624/ae8d0658-3c0a-4496-9786-0a0a8a299e35)


效果如下：

![Screenshot from 2024-02-22 17-28-08](https://github.com/fishjar/kiss-translator/assets/1157624/89f36c10-91e1-48b0-a544-4e7d69c5a711)

**Comment by fishjar** [comment]
> 1、这个很可能是github代码的问题，类似这个 issue： [#50 (comment)](https://github.com/fishjar/kiss-translator/issues/50#issuecomment-1825126129)
> 
> 2、在iframe中发送消息给parent会触发问题，接受消息则没有问题，所以应该可以修复一下，ifame中只单向接受消息即可。
> 
> 3、关于iframe页面，其实之前就有个纠结的问题，即iframe中的规则要不要和parent的规则共用。
> 
> * 如果规则不共用，但快捷键等操作肯定要共用，则可能会造成`是否翻译`的状态混乱。
> * 如果共用的话也不太合理，ifame和parent页面元素结构完全不同，规则大相径庭。
> 
> 之前的做法是选择共用，所以iframe需要从parent获取规则信息。通过修复这个bug，顺便改变一下这个规则，即iframe和parent规则分开定义，状态混淆的问题可以设置一致的初始状态即可避免。

规则分开定义还有个好处，即使单独打开irame页面的链接，也将按照规则定义翻译。
比如 [打开页面](https://notebooks.githubusercontent.com/view/ipynb?browser=chrome&bypass_fastly=true&color_mode=auto&commit=04e28168d820eea3a1ff1e098078323e7b48648b&device=unknown_device&docs_host=https%3A%2F%2Fdocs.github.com&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f4c61796f75742d5061727365722f6c61796f75742d7061727365722f303465323831363864383230656561336131666631653039383037383332336537623438363438622f6578616d706c65732f4f43522532305461626c6573253230616e6425323050617273652532307468652532304f75747075742e6970796e62&logged_in=true&nwo=Layout-Parser%2Flayout-parser&path=examples%2FOCR+Tables+and+Parse+the+Output.ipynb&platform=linux&repository_id=271377309&repository_type=Repository&version=110#9241ab7f-28a5-4cd2-b2fe-9e03bbabde8a)

**Comment by Long0x0** [comment]
嗯，还是分开定义更合理一些。
另外选择器能不能支持引用全局选择器呢，类似于`#notebook-container :is(GLOBAL_SELECTOR)`，这样自定义规则就不用再写一遍。

**Comment by fishjar** [comment]
> 另外选择器能不能支持引用全局选择器呢，类似于`#notebook-container :is(GLOBAL_SELECTOR)`，这样自定义规则就不用再写一遍。

需要时到全局规则或订阅规则复制一份即可，不算太麻烦。

而且如果这样的话，还需要一个能编辑 `GLOBAL_SELECTOR` 定义的地方，暂时还是不增加这个特性吧。
