### ISSUE TITLE
悬浮球位置未记忆

### ISSUE THREAD

**Issue by jqtmviyu** [fishjar/kiss-translator#98]
os: macos 12.7
浏览器: floorp 11.10.5 (firfox)
拓展版本: 1.8.3
问题描述: 重启系统后, 悬浮球的位置又回到顶部居中, 不能记住上次拖拽的位置.

排查1: 直接重启浏览器能记住.

**Comment by fishjar** [comment]
其他设置会恢复默认吗？

**Comment by jqtmviyu** [comment]
> 其他设置会恢复默认吗？

规则设置还保留着.

似乎和窗口缩放有关.我使用了yabai平铺桌面, 会自动缩放浏览器窗口大小.

复现: 手动缩放和移动浏览器到不同desktop的过程中, 悬浮球的位置会发生变化.

**Comment by fishjar** [comment]
那就是这个原因了，悬浮球的位置计算做了防抖处理，有个延时，所以如果窗口改变太快的话，可能会跑到另一边去。
