### ISSUE TITLE
输入框翻译快捷键设置以及输入框原文框点击焦点偏移问题

### ISSUE THREAD

**Issue by yws112358** [fishjar/kiss-translator#99]
你好，今天才从GreesyFork发现你的翻译插件，进而安装的edge插件。发现一些用起来怪异的地方：
1.设置-输入框翻译-触发翻译快捷键 设置了之后，操作无反应。（如 alt+z alt+v）
2.翻译对话框里，原文框鼠标需要稍微靠上才能点击进入编辑状态。
另外同步功能webdav是怎么部署的？有个alist的webdav能用吗？未设置下，补丁设置里的同步是同步到哪的？

**Comment by yws112358** [comment]
第一个问题  发现需要设置扩展快捷键生效  扩展内设置不行
第二个问题别人提过  奇怪了

**Comment by fishjar** [comment]
1、试了一下，第二个问题是一个bug，需要修复。
2、webdav同步仅测试过[坚果云](https://www.jianguoyun.com/)，不过按理只要符合这个协议的接口都可以
3、补丁设置的同步实际和订阅规则同步一样，是从[社区维护规](https://github.com/fishjar/kiss-rules)则同步至本地，不过这个补丁同步的功能下个版本没有了，补丁设置合并到规则设置了，edge审核比较慢，你可以到[谷歌的市场](https://chrome.google.com/webstore/detail/kiss-translator/bdiifdefkgmcblbcghdlonllpjhhjgof?hl=zh-CN)下载新版本(v1.8.4)

**Comment by fishjar** [comment]
新版已修复。
